// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// GiftcardCheckout is an object representing the database table.
type GiftcardCheckout struct {
	ID         string `boil:"id" json:"id" toml:"id" yaml:"id"`
	GiftcardID string `boil:"giftcard_id" json:"giftcard_id" toml:"giftcard_id" yaml:"giftcard_id"`
	CheckoutID string `boil:"checkout_id" json:"checkout_id" toml:"checkout_id" yaml:"checkout_id"`

	R *giftcardCheckoutR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L giftcardCheckoutL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var GiftcardCheckoutColumns = struct {
	ID         string
	GiftcardID string
	CheckoutID string
}{
	ID:         "id",
	GiftcardID: "giftcard_id",
	CheckoutID: "checkout_id",
}

var GiftcardCheckoutTableColumns = struct {
	ID         string
	GiftcardID string
	CheckoutID string
}{
	ID:         "giftcard_checkouts.id",
	GiftcardID: "giftcard_checkouts.giftcard_id",
	CheckoutID: "giftcard_checkouts.checkout_id",
}

// Generated where

var GiftcardCheckoutWhere = struct {
	ID         whereHelperstring
	GiftcardID whereHelperstring
	CheckoutID whereHelperstring
}{
	ID:         whereHelperstring{field: "\"giftcard_checkouts\".\"id\""},
	GiftcardID: whereHelperstring{field: "\"giftcard_checkouts\".\"giftcard_id\""},
	CheckoutID: whereHelperstring{field: "\"giftcard_checkouts\".\"checkout_id\""},
}

// GiftcardCheckoutRels is where relationship names are stored.
var GiftcardCheckoutRels = struct {
	Checkout string
	Giftcard string
}{
	Checkout: "Checkout",
	Giftcard: "Giftcard",
}

// giftcardCheckoutR is where relationships are stored.
type giftcardCheckoutR struct {
	Checkout *Checkout `boil:"Checkout" json:"Checkout" toml:"Checkout" yaml:"Checkout"`
	Giftcard *Giftcard `boil:"Giftcard" json:"Giftcard" toml:"Giftcard" yaml:"Giftcard"`
}

// NewStruct creates a new relationship struct
func (*giftcardCheckoutR) NewStruct() *giftcardCheckoutR {
	return &giftcardCheckoutR{}
}

func (r *giftcardCheckoutR) GetCheckout() *Checkout {
	if r == nil {
		return nil
	}
	return r.Checkout
}

func (r *giftcardCheckoutR) GetGiftcard() *Giftcard {
	if r == nil {
		return nil
	}
	return r.Giftcard
}

// giftcardCheckoutL is where Load methods for each relationship are stored.
type giftcardCheckoutL struct{}

var (
	giftcardCheckoutAllColumns            = []string{"id", "giftcard_id", "checkout_id"}
	giftcardCheckoutColumnsWithoutDefault = []string{"giftcard_id", "checkout_id"}
	giftcardCheckoutColumnsWithDefault    = []string{"id"}
	giftcardCheckoutPrimaryKeyColumns     = []string{"id"}
	giftcardCheckoutGeneratedColumns      = []string{}
)

type (
	// GiftcardCheckoutSlice is an alias for a slice of pointers to GiftcardCheckout.
	// This should almost always be used instead of []GiftcardCheckout.
	GiftcardCheckoutSlice []*GiftcardCheckout

	giftcardCheckoutQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	giftcardCheckoutType                 = reflect.TypeOf(&GiftcardCheckout{})
	giftcardCheckoutMapping              = queries.MakeStructMapping(giftcardCheckoutType)
	giftcardCheckoutPrimaryKeyMapping, _ = queries.BindMapping(giftcardCheckoutType, giftcardCheckoutMapping, giftcardCheckoutPrimaryKeyColumns)
	giftcardCheckoutInsertCacheMut       sync.RWMutex
	giftcardCheckoutInsertCache          = make(map[string]insertCache)
	giftcardCheckoutUpdateCacheMut       sync.RWMutex
	giftcardCheckoutUpdateCache          = make(map[string]updateCache)
	giftcardCheckoutUpsertCacheMut       sync.RWMutex
	giftcardCheckoutUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single giftcardCheckout record from the query.
func (q giftcardCheckoutQuery) One(exec boil.Executor) (*GiftcardCheckout, error) {
	o := &GiftcardCheckout{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(nil, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: failed to execute a one query for giftcard_checkouts")
	}

	return o, nil
}

// All returns all GiftcardCheckout records from the query.
func (q giftcardCheckoutQuery) All(exec boil.Executor) (GiftcardCheckoutSlice, error) {
	var o []*GiftcardCheckout

	err := q.Bind(nil, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to GiftcardCheckout slice")
	}

	return o, nil
}

// Count returns the count of all GiftcardCheckout records in the query.
func (q giftcardCheckoutQuery) Count(exec boil.Executor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count giftcard_checkouts rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q giftcardCheckoutQuery) Exists(exec boil.Executor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow(exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if giftcard_checkouts exists")
	}

	return count > 0, nil
}

// Checkout pointed to by the foreign key.
func (o *GiftcardCheckout) Checkout(mods ...qm.QueryMod) checkoutQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"token\" = ?", o.CheckoutID),
	}

	queryMods = append(queryMods, mods...)

	return Checkouts(queryMods...)
}

// Giftcard pointed to by the foreign key.
func (o *GiftcardCheckout) Giftcard(mods ...qm.QueryMod) giftcardQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.GiftcardID),
	}

	queryMods = append(queryMods, mods...)

	return Giftcards(queryMods...)
}

// LoadCheckout allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (giftcardCheckoutL) LoadCheckout(e boil.Executor, singular bool, maybeGiftcardCheckout interface{}, mods queries.Applicator) error {
	var slice []*GiftcardCheckout
	var object *GiftcardCheckout

	if singular {
		var ok bool
		object, ok = maybeGiftcardCheckout.(*GiftcardCheckout)
		if !ok {
			object = new(GiftcardCheckout)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeGiftcardCheckout)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeGiftcardCheckout))
			}
		}
	} else {
		s, ok := maybeGiftcardCheckout.(*[]*GiftcardCheckout)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeGiftcardCheckout)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeGiftcardCheckout))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &giftcardCheckoutR{}
		}
		args = append(args, object.CheckoutID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &giftcardCheckoutR{}
			}

			for _, a := range args {
				if a == obj.CheckoutID {
					continue Outer
				}
			}

			args = append(args, obj.CheckoutID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`checkouts`),
		qm.WhereIn(`checkouts.token in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Checkout")
	}

	var resultSlice []*Checkout
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Checkout")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for checkouts")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for checkouts")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Checkout = foreign
		if foreign.R == nil {
			foreign.R = &checkoutR{}
		}
		foreign.R.GiftcardCheckouts = append(foreign.R.GiftcardCheckouts, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CheckoutID == foreign.Token {
				local.R.Checkout = foreign
				if foreign.R == nil {
					foreign.R = &checkoutR{}
				}
				foreign.R.GiftcardCheckouts = append(foreign.R.GiftcardCheckouts, local)
				break
			}
		}
	}

	return nil
}

// LoadGiftcard allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (giftcardCheckoutL) LoadGiftcard(e boil.Executor, singular bool, maybeGiftcardCheckout interface{}, mods queries.Applicator) error {
	var slice []*GiftcardCheckout
	var object *GiftcardCheckout

	if singular {
		var ok bool
		object, ok = maybeGiftcardCheckout.(*GiftcardCheckout)
		if !ok {
			object = new(GiftcardCheckout)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeGiftcardCheckout)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeGiftcardCheckout))
			}
		}
	} else {
		s, ok := maybeGiftcardCheckout.(*[]*GiftcardCheckout)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeGiftcardCheckout)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeGiftcardCheckout))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &giftcardCheckoutR{}
		}
		args = append(args, object.GiftcardID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &giftcardCheckoutR{}
			}

			for _, a := range args {
				if a == obj.GiftcardID {
					continue Outer
				}
			}

			args = append(args, obj.GiftcardID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`giftcards`),
		qm.WhereIn(`giftcards.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.Query(e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Giftcard")
	}

	var resultSlice []*Giftcard
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Giftcard")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for giftcards")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for giftcards")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Giftcard = foreign
		if foreign.R == nil {
			foreign.R = &giftcardR{}
		}
		foreign.R.GiftcardCheckouts = append(foreign.R.GiftcardCheckouts, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.GiftcardID == foreign.ID {
				local.R.Giftcard = foreign
				if foreign.R == nil {
					foreign.R = &giftcardR{}
				}
				foreign.R.GiftcardCheckouts = append(foreign.R.GiftcardCheckouts, local)
				break
			}
		}
	}

	return nil
}

// SetCheckout of the giftcardCheckout to the related item.
// Sets o.R.Checkout to related.
// Adds o to related.R.GiftcardCheckouts.
func (o *GiftcardCheckout) SetCheckout(exec boil.Executor, insert bool, related *Checkout) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"giftcard_checkouts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"checkout_id"}),
		strmangle.WhereClause("\"", "\"", 2, giftcardCheckoutPrimaryKeyColumns),
	)
	values := []interface{}{related.Token, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CheckoutID = related.Token
	if o.R == nil {
		o.R = &giftcardCheckoutR{
			Checkout: related,
		}
	} else {
		o.R.Checkout = related
	}

	if related.R == nil {
		related.R = &checkoutR{
			GiftcardCheckouts: GiftcardCheckoutSlice{o},
		}
	} else {
		related.R.GiftcardCheckouts = append(related.R.GiftcardCheckouts, o)
	}

	return nil
}

// SetGiftcard of the giftcardCheckout to the related item.
// Sets o.R.Giftcard to related.
// Adds o to related.R.GiftcardCheckouts.
func (o *GiftcardCheckout) SetGiftcard(exec boil.Executor, insert bool, related *Giftcard) error {
	var err error
	if insert {
		if err = related.Insert(exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"giftcard_checkouts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"giftcard_id"}),
		strmangle.WhereClause("\"", "\"", 2, giftcardCheckoutPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, updateQuery)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	if _, err = exec.Exec(updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.GiftcardID = related.ID
	if o.R == nil {
		o.R = &giftcardCheckoutR{
			Giftcard: related,
		}
	} else {
		o.R.Giftcard = related
	}

	if related.R == nil {
		related.R = &giftcardR{
			GiftcardCheckouts: GiftcardCheckoutSlice{o},
		}
	} else {
		related.R.GiftcardCheckouts = append(related.R.GiftcardCheckouts, o)
	}

	return nil
}

// GiftcardCheckouts retrieves all the records using an executor.
func GiftcardCheckouts(mods ...qm.QueryMod) giftcardCheckoutQuery {
	mods = append(mods, qm.From("\"giftcard_checkouts\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"giftcard_checkouts\".*"})
	}

	return giftcardCheckoutQuery{q}
}

// FindGiftcardCheckout retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindGiftcardCheckout(exec boil.Executor, iD string, selectCols ...string) (*GiftcardCheckout, error) {
	giftcardCheckoutObj := &GiftcardCheckout{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"giftcard_checkouts\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(nil, exec, giftcardCheckoutObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: unable to select from giftcard_checkouts")
	}

	return giftcardCheckoutObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *GiftcardCheckout) Insert(exec boil.Executor, columns boil.Columns) error {
	if o == nil {
		return errors.New("model: no giftcard_checkouts provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(giftcardCheckoutColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	giftcardCheckoutInsertCacheMut.RLock()
	cache, cached := giftcardCheckoutInsertCache[key]
	giftcardCheckoutInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			giftcardCheckoutAllColumns,
			giftcardCheckoutColumnsWithDefault,
			giftcardCheckoutColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(giftcardCheckoutType, giftcardCheckoutMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(giftcardCheckoutType, giftcardCheckoutMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"giftcard_checkouts\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"giftcard_checkouts\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "model: unable to insert into giftcard_checkouts")
	}

	if !cached {
		giftcardCheckoutInsertCacheMut.Lock()
		giftcardCheckoutInsertCache[key] = cache
		giftcardCheckoutInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the GiftcardCheckout.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *GiftcardCheckout) Update(exec boil.Executor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	giftcardCheckoutUpdateCacheMut.RLock()
	cache, cached := giftcardCheckoutUpdateCache[key]
	giftcardCheckoutUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			giftcardCheckoutAllColumns,
			giftcardCheckoutPrimaryKeyColumns,
		)
		if len(wl) == 0 {
			return 0, errors.New("model: unable to update giftcard_checkouts, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"giftcard_checkouts\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, giftcardCheckoutPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(giftcardCheckoutType, giftcardCheckoutMapping, append(wl, giftcardCheckoutPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}
	var result sql.Result
	result, err = exec.Exec(cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update giftcard_checkouts row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by update for giftcard_checkouts")
	}

	if !cached {
		giftcardCheckoutUpdateCacheMut.Lock()
		giftcardCheckoutUpdateCache[key] = cache
		giftcardCheckoutUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q giftcardCheckoutQuery) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all for giftcard_checkouts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected for giftcard_checkouts")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o GiftcardCheckoutSlice) UpdateAll(exec boil.Executor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), giftcardCheckoutPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"giftcard_checkouts\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, giftcardCheckoutPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all in giftcardCheckout slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected all in update all giftcardCheckout")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *GiftcardCheckout) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("model: no giftcard_checkouts provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(giftcardCheckoutColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	giftcardCheckoutUpsertCacheMut.RLock()
	cache, cached := giftcardCheckoutUpsertCache[key]
	giftcardCheckoutUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			giftcardCheckoutAllColumns,
			giftcardCheckoutColumnsWithDefault,
			giftcardCheckoutColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			giftcardCheckoutAllColumns,
			giftcardCheckoutPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("model: unable to upsert giftcard_checkouts, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(giftcardCheckoutPrimaryKeyColumns))
			copy(conflict, giftcardCheckoutPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"giftcard_checkouts\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(giftcardCheckoutType, giftcardCheckoutMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(giftcardCheckoutType, giftcardCheckoutMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "model: unable to upsert giftcard_checkouts")
	}

	if !cached {
		giftcardCheckoutUpsertCacheMut.Lock()
		giftcardCheckoutUpsertCache[key] = cache
		giftcardCheckoutUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single GiftcardCheckout record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *GiftcardCheckout) Delete(exec boil.Executor) (int64, error) {
	if o == nil {
		return 0, errors.New("model: no GiftcardCheckout provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), giftcardCheckoutPrimaryKeyMapping)
	sql := "DELETE FROM \"giftcard_checkouts\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete from giftcard_checkouts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by delete for giftcard_checkouts")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q giftcardCheckoutQuery) DeleteAll(exec boil.Executor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("model: no giftcardCheckoutQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.Exec(exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from giftcard_checkouts")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for giftcard_checkouts")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o GiftcardCheckoutSlice) DeleteAll(exec boil.Executor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), giftcardCheckoutPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"giftcard_checkouts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, giftcardCheckoutPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}
	result, err := exec.Exec(sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from giftcardCheckout slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for giftcard_checkouts")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *GiftcardCheckout) Reload(exec boil.Executor) error {
	ret, err := FindGiftcardCheckout(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *GiftcardCheckoutSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := GiftcardCheckoutSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), giftcardCheckoutPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"giftcard_checkouts\".* FROM \"giftcard_checkouts\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, giftcardCheckoutPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(nil, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in GiftcardCheckoutSlice")
	}

	*o = slice

	return nil
}

// GiftcardCheckoutExists checks if the GiftcardCheckout row exists.
func GiftcardCheckoutExists(exec boil.Executor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"giftcard_checkouts\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, iD)
	}
	row := exec.QueryRow(sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if giftcard_checkouts exists")
	}

	return exists, nil
}

// Exists checks if the GiftcardCheckout row exists.
func (o *GiftcardCheckout) Exists(exec boil.Executor) (bool, error) {
	return GiftcardCheckoutExists(exec, o.ID)
}
