// Code generated by "make app-layers"
// DO NOT EDIT

package sub_app_iface

import (
	"github.com/sitename/sitename/model"
	"github.com/sitename/sitename/model/channel"
)

// ChannelService contains methods for working with channels
type ChannelService interface {
	// ChannelByOption returns a channel that satisfies given options
	ChannelByOption(option *channel.ChannelFilterOption) (*channel.Channel, *model.AppError)
	// ChannelsByOption returns a list of channels by given options
	ChannelsByOption(option *channel.ChannelFilterOption) ([]*channel.Channel, *model.AppError)
	// CleanChannel
	CleanChannel(channelSlug *string) (*channel.Channel, *model.AppError)
	// GetChannelBySlug returns a channel with given slug
	GetChannelBySlug(slug string) (*channel.Channel, *model.AppError)
	// GetDefaultActiveChannel
	GetDefaultActiveChannel() (*channel.Channel, *model.AppError)
	// ValidateChannel check if a channel with given slug is active
	ValidateChannel(channelSlug string) (*channel.Channel, *model.AppError)
	GetDefaultChannel() (*channel.Channel, *model.AppError)
	GetDefaultChannelSlugOrGraphqlError() (string, *model.AppError)
}
