// Code generated by "make app-layers"
// DO NOT EDIT

package sub_app_iface

import (
	goprices "github.com/site-name/go-prices"
	"github.com/sitename/sitename/model"
	"github.com/sitename/sitename/model/checkout"
	"github.com/sitename/sitename/model/order"
	"github.com/sitename/sitename/model/shipping"
)

// ShippingService contains methods for working with shippings
type ShippingService interface {
	// ApplicableShippingMethodsForCheckout finds all applicable shipping methods for given checkout, based on given additional arguments
	ApplicableShippingMethodsForCheckout(ckout *checkout.Checkout, channelID string, price *goprices.Money, countryCode string, lines []*checkout.CheckoutLineInfo) ([]*shipping.ShippingMethod, *model.AppError)
	// ApplicableShippingMethodsForOrder finds all applicable shippingmethods for given order, based on other arguments passed in
	ApplicableShippingMethodsForOrder(oder *order.Order, channelID string, price *goprices.Money, countryCode string, lines []*checkout.CheckoutLineInfo) ([]*shipping.ShippingMethod, *model.AppError)
	// DefaultShippingZoneExists returns all shipping zones that have Ids differ than given shippingZoneID and has `Default` properties equal to true
	DefaultShippingZoneExists(shippingZoneID string) ([]*shipping.ShippingZone, *model.AppError)
	// FilterShippingMethodsByPostalCodeRules Filter shipping methods for given address by postal code rules.
	FilterShippingMethodsByPostalCodeRules(shippingMethods []*shipping.ShippingMethod, shippingAddressID string) ([]*shipping.ShippingMethod, *model.AppError)
	// GetCountriesWithoutShippingZone Returns country codes that are not assigned to any shipping zone.
	GetCountriesWithoutShippingZone() ([]string, *model.AppError)
	// ShippingMethodByOption returns a shipping method with given options
	ShippingMethodByOption(option *shipping.ShippingMethodFilterOption) (*shipping.ShippingMethod, *model.AppError)
	// ShippingMethodChannelListingsByOption returns a list of shipping method channel listings by given option
	ShippingMethodChannelListingsByOption(option *shipping.ShippingMethodChannelListingFilterOption) ([]*shipping.ShippingMethodChannelListing, *model.AppError)
	// ShippingZonesByOption returns all shipping zones that satisfy given options
	ShippingZonesByOption(option *shipping.ShippingZoneFilterOption) ([]*shipping.ShippingZone, *model.AppError)
}
