output   = "model"
wipe     = true
no-tests = true
add-enum-types = true
pkgname = "model"
tracing = true
no-auto-timestamps = true
no-hooks = true
debug = false

[psql]
  dbname = "sitename_test"
  host   = "localhost"
  port   = 5432
  user   = "minh"
  pass   = "anhyeuem98"
  sslmode = "disable"
  blacklist = ["migrations", "other"]
