output   = "models"
wipe     = true
no-tests = false
add-enum-types = true
pkgname = "models"
tracing = true

[psql]
  dbname = "sitename_test"
  host   = "localhost"
  port   = 5432
  user   = "minh"
  pass   = "anhyeuem98"
  sslmode = "disable"
  blacklist = ["migrations", "other"]
