package model_helper

import (
	"crypto/sha1"
	"net/http"
	"regexp"
	"strings"

	"github.com/google/uuid"
	"github.com/samber/lo"
	"github.com/sitename/sitename/model"
)

// constants for access http(s) requests's headers
const (
	HeaderRequestId          = "X-Request-ID"
	HeaderVersionId          = "X-Version-ID"
	HeaderClusterId          = "X-Cluster-ID"
	HeaderAcceptEncoding     = "Accept-Encoding"
	HeaderAcceptLanguage     = "Accept-Language"
	HeaderUserAgent          = "User-Agent"
	HeaderRemoteAddress      = "Remote Address"
	HeaderEtagServer         = "ETag"
	HeaderEtagClient         = "If-None-Match"
	HeaderForwarded          = "X-Forwarded-For"
	HeaderRealIp             = "X-Real-IP"
	HeaderForwardedProto     = "X-Forwarded-Proto"
	HeaderToken              = "token"
	HeaderCsrfToken          = "X-CSRF-Token"
	HeaderBearer             = "BEARER"
	HeaderAuth               = "Authorization"
	HeaderCloudToken         = "X-Cloud-Token"
	HeaderRemoteClusterToken = "X-RemoteCluster-Token"
	HeaderRemoteClusterId    = "X-RemoteCluster-Id"
	HeaderRequestedWith      = "X-Requested-With"
	HeaderRequestedWith_XML  = "XMLHttpRequest"
	HeaderRange              = "Range"
	STATUS                   = "status"
	STATUS_OK                = "OK"
	STATUS_FAIL              = "FAIL"
	STATUS_UNHEALTHY         = "UNHEALTHY"
	STATUS_REMOVE            = "REMOVE"
	CLIENT_DIR               = "client"
	AppIdPrefix              = "app"
)

var UUID_NAMESPACE = uuid.New()

// Refer to https://github.com/nu7hatch/gouuid/blob/179d4d0c4d8d407a32af483c2354df1d2c91e6c3/uuid.go#L113 for details
func NewUUIDv5(nameSpace *uuid.UUID, name []byte) uuid.UUID {
	u := new(uuid.UUID)

	hash := sha1.New()
	hash.Write(nameSpace[:])
	hash.Write(name)
	copy(u[:], hash.Sum([]byte{})[:16])
	u[8] = (u[8] | 0x40) & 0x7F
	u[6] = (u[6] & 0xF) | (5 << 4)

	return *u
}

func GetClientId(r *http.Request) uuid.UUID {
	headers := []string{HeaderAcceptEncoding, HeaderAcceptLanguage, HeaderUserAgent, HeaderForwarded, HeaderRemoteAddress}
	headers = lo.Map(headers, func(item string, _ int) string {
		return r.Header.Get(item)
	})
	name := strings.Join(headers, "_")
	return NewUUIDv5(&UUID_NAMESPACE, []byte(name))
}

type TimePeriodType string

// time period types
const (
	DAY   TimePeriodType = "day"
	WEEK  TimePeriodType = "week"
	MONTH TimePeriodType = "month"
	YEAR  TimePeriodType = "year"
)

func (t TimePeriodType) IsValid() bool {
	switch t {
	case DAY, WEEK, MONTH, YEAR:
		return true
	default:
		return false
	}
}

const (
	ProductNotPublishedAppErrID       = "app.checkout.product_unpublished.app_error"
	InvalidArgumentAppErrorID         = "app.invalid_arguments.app_error" // InvalidArgumentAppErrorID used when creating app errors on invalid argument
	ErrorCalculatingMoneyErrorID      = "app.error_calculating_money.app_error"
	ErrorCreatingTransactionErrorID   = "app.error_creating_transaction.app_error"
	ErrorCommittingTransactionErrorID = "app.error_committing_transaction.app_error"
	ErrorCalculatingMeasurementID     = "app.error_calculating_measurement.app_error"
	ErrorMarshallingDataID            = "app.error_marshalling_data.app_error"
	ErrorUnMarshallingDataID          = "app.error_unmarshalling_data.app_error"
)

// some default values for model fields
const (
	TimeZone                = "UTC"
	USER_AUTH_SERVICE_EMAIL = "email"
	DEFAULT_CURRENCY        = model.CurrencyUSD
	USER_NAME_MAX_LENGTH    = 64
	USER_EMAIL_MAX_LENGTH   = 128
	USER_NAME_MIN_LENGTH    = 1
	DEFAULT_LOCALE          = model.LanguageCodeEN // this is default language also
	DEFAULT_COUNTRY         = model.CountryCodeUS
	// URL_LINK_MAX_LENGTH     = 200
	// SINGLE_COUNTRY_CODE_MAX_LENGTH = 5
	// WEIGHT_UNIT_MAX_LENGTH         = 5
	// IP_ADDRESS_MAX_LENGTH          = 39
	// LANGUAGE_CODE_MAX_LENGTH       = 5
	// CURRENCY_CODE_MAX_LENGTH       = 3
)

var (
	Countries                     map[model.CountryCode]string  // countries supported by app
	Languages                     map[model.LanguageCode]string // Languages supported by app
	MULTIPLE_COUNTRIES_MAX_LENGTH int                           // some model"s country fields contains multiple countries

	ValidUsernameChars  = regexp.MustCompile(`^[a-z0-9\.\-_]+$`) // regexp for username validation
	RestrictedUsernames map[string]bool                          // usernames that cannot be used

	// usernames that can only be used by system
	ReservedName = []string{
		"admin",
		"api",
		"channel",
		"claim",
		"error",
		"files",
		"help",
		"landing",
		"login",
		"mfa",
		"oauth",
		"plug",
		"plugins",
		"post",
		"signup",
		"sitename",
	}
)

// initConsts is called by init() function that located in /model/init.go
func initConsts() {
	Countries = map[model.CountryCode]string{
		model.CountryCodeAF: "Afghanistan",
		model.CountryCodeAX: "Aland Islands",
		model.CountryCodeAL: "Albania",
		model.CountryCodeDZ: "Algeria",
		model.CountryCodeAS: "American Samoa",
		model.CountryCodeAD: "Andorra",
		model.CountryCodeAO: "Angola",
		model.CountryCodeAI: "Anguilla",
		model.CountryCodeAQ: "Antarctica",
		model.CountryCodeAG: "Antigua and Barbuda",
		model.CountryCodeAR: "Argentina",
		model.CountryCodeAM: "Armenia",
		model.CountryCodeAW: "Aruba",
		model.CountryCodeAU: "Australia",
		model.CountryCodeAT: "Austria",
		model.CountryCodeAZ: "Azerbaijan",
		model.CountryCodeBS: "Bahamas",
		model.CountryCodeBH: "Bahrain",
		model.CountryCodeBD: "Bangladesh",
		model.CountryCodeBB: "Barbados",
		model.CountryCodeBY: "Belarus",
		model.CountryCodeBE: "Belgium",
		model.CountryCodeBZ: "Belize",
		model.CountryCodeBJ: "Benin",
		model.CountryCodeBM: "Bermuda",
		model.CountryCodeBT: "Bhutan",
		model.CountryCodeBO: "Bolivia",
		model.CountryCodeBQ: "Bonaire, Sint Eustatius and Saba",
		model.CountryCodeBA: "Bosnia and Herzegovina",
		model.CountryCodeBW: "Botswana",
		model.CountryCodeBV: "Bouvet Island",
		model.CountryCodeBR: "Brazil",
		model.CountryCodeIO: "British Indian Ocean Territory",
		model.CountryCodeBN: "Brunei",
		model.CountryCodeBG: "Bulgaria",
		model.CountryCodeBF: "Burkina Faso",
		model.CountryCodeBI: "Burundi",
		model.CountryCodeCV: "Cabo Verde",
		model.CountryCodeKH: "Cambodia",
		model.CountryCodeCM: "Cameroon",
		model.CountryCodeCA: "Canada",
		model.CountryCodeKY: "Cayman Islands",
		model.CountryCodeCF: "Central African Republic",
		model.CountryCodeTD: "Chad",
		model.CountryCodeCL: "Chile",
		model.CountryCodeCN: "China",
		model.CountryCodeCX: "Christmas Island",
		model.CountryCodeCC: "Cocos (Keeling) Islands",
		model.CountryCodeCO: "Colombia",
		model.CountryCodeKM: "Comoros",
		model.CountryCodeCG: "Congo",
		model.CountryCodeCD: "Congo (the Democratic Republic of the)",
		model.CountryCodeCK: "Cook Islands",
		model.CountryCodeCR: "Costa Rica",
		model.CountryCodeCI: "Côte d'Ivoire",
		model.CountryCodeHR: "Croatia",
		model.CountryCodeCU: "Cuba",
		model.CountryCodeCW: "Curaçao",
		model.CountryCodeCY: "Cyprus",
		model.CountryCodeCZ: "Czechia",
		model.CountryCodeDK: "Denmark",
		model.CountryCodeDJ: "Djibouti",
		model.CountryCodeDM: "Dominica",
		model.CountryCodeDO: "Dominican Republic",
		model.CountryCodeEC: "Ecuador",
		model.CountryCodeEG: "Egypt",
		model.CountryCodeSV: "El Salvador",
		model.CountryCodeGQ: "Equatorial Guinea",
		model.CountryCodeER: "Eritrea",
		model.CountryCodeEE: "Estonia",
		model.CountryCodeSZ: "Eswatini",
		model.CountryCodeET: "Ethiopia",
		model.CountryCodeFK: "Falkland Islands (Malvinas)",
		model.CountryCodeFO: "Faroe Islands",
		model.CountryCodeFJ: "Fiji",
		model.CountryCodeFI: "Finland",
		model.CountryCodeFR: "France",
		model.CountryCodeGF: "French Guiana",
		model.CountryCodePF: "French Polynesia",
		model.CountryCodeTF: "French Southern Territories",
		model.CountryCodeGA: "Gabon",
		model.CountryCodeGM: "Gambia",
		model.CountryCodeGE: "Georgia",
		model.CountryCodeDE: "Germany",
		model.CountryCodeGH: "Ghana",
		model.CountryCodeGI: "Gibraltar",
		model.CountryCodeGR: "Greece",
		model.CountryCodeGL: "Greenland",
		model.CountryCodeGD: "Grenada",
		model.CountryCodeGP: "Guadeloupe",
		model.CountryCodeGU: "Guam",
		model.CountryCodeGT: "Guatemala",
		model.CountryCodeGG: "Guernsey",
		model.CountryCodeGN: "Guinea",
		model.CountryCodeGW: "Guinea-Bissau",
		model.CountryCodeGY: "Guyana",
		model.CountryCodeHT: "Haiti",
		model.CountryCodeHM: "Heard Island and McDonald Islands",
		model.CountryCodeVA: "Holy See",
		model.CountryCodeHN: "Honduras",
		model.CountryCodeHK: "Hong Kong",
		model.CountryCodeHU: "Hungary",
		model.CountryCodeIS: "Iceland",
		model.CountryCodeIN: "India",
		model.CountryCodeID: "Indonesia",
		model.CountryCodeIR: "Iran",
		model.CountryCodeIQ: "Iraq",
		model.CountryCodeIE: "Ireland",
		model.CountryCodeIM: "Isle of Man",
		model.CountryCodeIL: "Israel",
		model.CountryCodeIT: "Italy",
		model.CountryCodeJM: "Jamaica",
		model.CountryCodeJP: "Japan",
		model.CountryCodeJE: "Jersey",
		model.CountryCodeJO: "Jordan",
		model.CountryCodeKZ: "Kazakhstan",
		model.CountryCodeKE: "Kenya",
		model.CountryCodeKI: "Kiribati",
		model.CountryCodeKP: "North Korea",
		model.CountryCodeKR: "South Korea",
		model.CountryCodeKW: "Kuwait",
		model.CountryCodeKG: "Kyrgyzstan",
		model.CountryCodeLA: "Laos",
		model.CountryCodeLV: "Latvia",
		model.CountryCodeLB: "Lebanon",
		model.CountryCodeLS: "Lesotho",
		model.CountryCodeLR: "Liberia",
		model.CountryCodeLY: "Libya",
		model.CountryCodeLI: "Liechtenstein",
		model.CountryCodeLT: "Lithuania",
		model.CountryCodeLU: "Luxembourg",
		model.CountryCodeMO: "Macao",
		model.CountryCodeMG: "Madagascar",
		model.CountryCodeMW: "Malawi",
		model.CountryCodeMY: "Malaysia",
		model.CountryCodeMV: "Maldives",
		model.CountryCodeML: "Mali",
		model.CountryCodeMT: "Malta",
		model.CountryCodeMH: "Marshall Islands",
		model.CountryCodeMQ: "Martinique",
		model.CountryCodeMR: "Mauritania",
		model.CountryCodeMU: "Mauritius",
		model.CountryCodeYT: "Mayotte",
		model.CountryCodeMX: "Mexico",
		model.CountryCodeFM: "Micronesia (Federated States of)",
		model.CountryCodeMD: "Moldova",
		model.CountryCodeMC: "Monaco",
		model.CountryCodeMN: "Mongolia",
		model.CountryCodeME: "Montenegro",
		model.CountryCodeMS: "Montserrat",
		model.CountryCodeMA: "Morocco",
		model.CountryCodeMZ: "Mozambique",
		model.CountryCodeMM: "Myanmar",
		model.CountryCodeNA: "Namibia",
		model.CountryCodeNR: "Nauru",
		model.CountryCodeNP: "Nepal",
		model.CountryCodeNL: "Netherlands",
		model.CountryCodeNC: "New Caledonia",
		model.CountryCodeNZ: "New Zealand",
		model.CountryCodeNI: "Nicaragua",
		model.CountryCodeNE: "Niger",
		model.CountryCodeNG: "Nigeria",
		model.CountryCodeNU: "Niue",
		model.CountryCodeNF: "Norfolk Island",
		model.CountryCodeMK: "North Macedonia",
		model.CountryCodeMP: "Northern Mariana Islands",
		model.CountryCodeNO: "Norway",
		model.CountryCodeOM: "Oman",
		model.CountryCodePK: "Pakistan",
		model.CountryCodePW: "Palau",
		model.CountryCodePS: "Palestine, State of",
		model.CountryCodePA: "Panama",
		model.CountryCodePG: "Papua New Guinea",
		model.CountryCodePY: "Paraguay",
		model.CountryCodePE: "Peru",
		model.CountryCodePH: "Philippines",
		model.CountryCodePN: "Pitcairn",
		model.CountryCodePL: "Poland",
		model.CountryCodePT: "Portugal",
		model.CountryCodePR: "Puerto Rico",
		model.CountryCodeQA: "Qatar",
		model.CountryCodeRE: "Réunion",
		model.CountryCodeRO: "Romania",
		model.CountryCodeRU: "Russia",
		model.CountryCodeRW: "Rwanda",
		model.CountryCodeBL: "Saint Barthélemy",
		model.CountryCodeSH: "Saint Helena, Ascension and Tristan da Cunha",
		model.CountryCodeKN: "Saint Kitts and Nevis",
		model.CountryCodeLC: "Saint Lucia",
		model.CountryCodeMF: "Saint Martin (French part)",
		model.CountryCodePM: "Saint Pierre and Miquelon",
		model.CountryCodeVC: "Saint Vincent and the Grenadines",
		model.CountryCodeWS: "Samoa",
		model.CountryCodeSM: "San Marino",
		model.CountryCodeST: "Sao Tome and Principe",
		model.CountryCodeSA: "Saudi Arabia",
		model.CountryCodeSN: "Senegal",
		model.CountryCodeRS: "Serbia",
		model.CountryCodeSC: "Seychelles",
		model.CountryCodeSL: "Sierra Leone",
		model.CountryCodeSG: "Singapore",
		model.CountryCodeSX: "Sint Maarten (Dutch part)",
		model.CountryCodeSK: "Slovakia",
		model.CountryCodeSI: "Slovenia",
		model.CountryCodeSB: "Solomon Islands",
		model.CountryCodeSO: "Somalia",
		model.CountryCodeZA: "South Africa",
		model.CountryCodeGS: "South Georgia and the South Sandwich Islands",
		model.CountryCodeSS: "South Sudan",
		model.CountryCodeES: "Spain",
		model.CountryCodeLK: "Sri Lanka",
		model.CountryCodeSD: "Sudan",
		model.CountryCodeSR: "Suriname",
		model.CountryCodeSJ: "Svalbard and Jan Mayen",
		model.CountryCodeSE: "Sweden",
		model.CountryCodeCH: "Switzerland",
		model.CountryCodeSY: "Syria",
		model.CountryCodeTW: "Taiwan",
		model.CountryCodeTJ: "Tajikistan",
		model.CountryCodeTZ: "Tanzania",
		model.CountryCodeTH: "Thailand",
		model.CountryCodeTL: "Timor-Leste",
		model.CountryCodeTG: "Togo",
		model.CountryCodeTK: "Tokelau",
		model.CountryCodeTO: "Tonga",
		model.CountryCodeTT: "Trinidad and Tobago",
		model.CountryCodeTN: "Tunisia",
		model.CountryCodeTR: "Turkey",
		model.CountryCodeTM: "Turkmenistan",
		model.CountryCodeTC: "Turks and Caicos Islands",
		model.CountryCodeTV: "Tuvalu",
		model.CountryCodeUG: "Uganda",
		model.CountryCodeUA: "Ukraine",
		model.CountryCodeAE: "United Arab Emirates",
		model.CountryCodeGB: "United Kingdom",
		model.CountryCodeUM: "United States Minor Outlying Islands",
		model.CountryCodeUS: "United States of America",
		model.CountryCodeUY: "Uruguay",
		model.CountryCodeUZ: "Uzbekistan",
		model.CountryCodeVU: "Vanuatu",
		model.CountryCodeVE: "Venezuela",
		model.CountryCodeVN: "Vietnam",
		model.CountryCodeVG: "Virgin Islands (British)",
		model.CountryCodeVI: "Virgin Islands (U.S.)",
		model.CountryCodeWF: "Wallis and Futuna",
		model.CountryCodeEH: "Western Sahara",
		model.CountryCodeYE: "Yemen",
		model.CountryCodeZM: "Zambia",
		model.CountryCodeZW: "Zimbabwe",
		model.CountryCodeEU: "European Union",
	}

	Languages = map[model.LanguageCode]string{
		model.LanguageCodeAF:             "Afrikaans",
		model.LanguageCodeAF_NA:          "Afrikaans (Namibia)",
		model.LanguageCodeAF_ZA:          "Afrikaans (South Africa)",
		model.LanguageCodeAGQ:            "Aghem",
		model.LanguageCodeAGQ_CM:         "Aghem (Cameroon)",
		model.LanguageCodeAK:             "Akan",
		model.LanguageCodeAK_GH:          "Akan (Ghana)",
		model.LanguageCodeAM:             "Amharic",
		model.LanguageCodeAM_ET:          "Amharic (Ethiopia)",
		model.LanguageCodeAR:             "Arabic",
		model.LanguageCodeAR_AE:          "Arabic (United Arab Emirates)",
		model.LanguageCodeAR_BH:          "Arabic (Bahrain)",
		model.LanguageCodeAR_DJ:          "Arabic (Djibouti)",
		model.LanguageCodeAR_DZ:          "Arabic (Algeria)",
		model.LanguageCodeAR_EG:          "Arabic (Egypt)",
		model.LanguageCodeAR_EH:          "Arabic (Western Sahara)",
		model.LanguageCodeAR_ER:          "Arabic (Eritrea)",
		model.LanguageCodeAR_IL:          "Arabic (Israel)",
		model.LanguageCodeAR_IQ:          "Arabic (Iraq)",
		model.LanguageCodeAR_JO:          "Arabic (Jordan)",
		model.LanguageCodeAR_KM:          "Arabic (Comoros)",
		model.LanguageCodeAR_KW:          "Arabic (Kuwait)",
		model.LanguageCodeAR_LB:          "Arabic (Lebanon)",
		model.LanguageCodeAR_LY:          "Arabic (Libya)",
		model.LanguageCodeAR_MA:          "Arabic (Morocco)",
		model.LanguageCodeAR_MR:          "Arabic (Mauritania)",
		model.LanguageCodeAR_OM:          "Arabic (Oman)",
		model.LanguageCodeAR_PS:          "Arabic (Palestinian Territories)",
		model.LanguageCodeAR_QA:          "Arabic (Qatar)",
		model.LanguageCodeAR_SA:          "Arabic (Saudi Arabia)",
		model.LanguageCodeAR_SD:          "Arabic (Sudan)",
		model.LanguageCodeAR_SO:          "Arabic (Somalia)",
		model.LanguageCodeAR_SS:          "Arabic (South Sudan)",
		model.LanguageCodeAR_SY:          "Arabic (Syria)",
		model.LanguageCodeAR_TD:          "Arabic (Chad)",
		model.LanguageCodeAR_TN:          "Arabic (Tunisia)",
		model.LanguageCodeAR_YE:          "Arabic (Yemen)",
		model.LanguageCodeAS:             "Assamese",
		model.LanguageCodeAS_IN:          "Assamese (India)",
		model.LanguageCodeASA:            "Asu",
		model.LanguageCodeASA_TZ:         "Asu (Tanzania)",
		model.LanguageCodeAST:            "Asturian",
		model.LanguageCodeAST_ES:         "Asturian (Spain)",
		model.LanguageCodeAZ:             "Azerbaijani",
		model.LanguageCodeAZ_CYRL:        "Azerbaijani (Cyrillic)",
		model.LanguageCodeAZ_CYRL_AZ:     "Azerbaijani (Cyrillic, Azerbaijan)",
		model.LanguageCodeAZ_LATN:        "Azerbaijani (Latin)",
		model.LanguageCodeAZ_LATN_AZ:     "Azerbaijani (Latin, Azerbaijan)",
		model.LanguageCodeBAS:            "Basaa",
		model.LanguageCodeBAS_CM:         "Basaa (Cameroon)",
		model.LanguageCodeBE:             "Belarusian",
		model.LanguageCodeBE_BY:          "Belarusian (Belarus)",
		model.LanguageCodeBEM:            "Bemba",
		model.LanguageCodeBEM_ZM:         "Bemba (Zambia)",
		model.LanguageCodeBEZ:            "Bena",
		model.LanguageCodeBEZ_TZ:         "Bena (Tanzania)",
		model.LanguageCodeBG:             "Bulgarian",
		model.LanguageCodeBG_BG:          "Bulgarian (Bulgaria)",
		model.LanguageCodeBM:             "Bambara",
		model.LanguageCodeBM_ML:          "Bambara (Mali)",
		model.LanguageCodeBN:             "Bangla",
		model.LanguageCodeBN_BD:          "Bangla (Bangladesh)",
		model.LanguageCodeBN_IN:          "Bangla (India)",
		model.LanguageCodeBO:             "Tibetan",
		model.LanguageCodeBO_CN:          "Tibetan (China)",
		model.LanguageCodeBO_IN:          "Tibetan (India)",
		model.LanguageCodeBR:             "Breton",
		model.LanguageCodeBR_FR:          "Breton (France)",
		model.LanguageCodeBRX:            "Bodo",
		model.LanguageCodeBRX_IN:         "Bodo (India)",
		model.LanguageCodeBS:             "Bosnian",
		model.LanguageCodeBS_CYRL:        "Bosnian (Cyrillic)",
		model.LanguageCodeBS_CYRL_BA:     "Bosnian (Cyrillic, Bosnia & Herzegovina)",
		model.LanguageCodeBS_LATN:        "Bosnian (Latin)",
		model.LanguageCodeBS_LATN_BA:     "Bosnian (Latin, Bosnia & Herzegovina)",
		model.LanguageCodeCA:             "Catalan",
		model.LanguageCodeCA_AD:          "Catalan (Andorra)",
		model.LanguageCodeCA_ES:          "Catalan (Spain)",
		model.LanguageCodeCA_ES_VALENCIA: "Catalan (Spain, Valencian)",
		model.LanguageCodeCA_FR:          "Catalan (France)",
		model.LanguageCodeCA_IT:          "Catalan (Italy)",
		model.LanguageCodeCCP:            "Chakma",
		model.LanguageCodeCCP_BD:         "Chakma (Bangladesh)",
		model.LanguageCodeCCP_IN:         "Chakma (India)",
		model.LanguageCodeCE:             "Chechen",
		model.LanguageCodeCE_RU:          "Chechen (Russia)",
		model.LanguageCodeCEB:            "Cebuano",
		model.LanguageCodeCEB_PH:         "Cebuano (Philippines)",
		model.LanguageCodeCGG:            "Chiga",
		model.LanguageCodeCGG_UG:         "Chiga (Uganda)",
		model.LanguageCodeCHR:            "Cherokee",
		model.LanguageCodeCHR_US:         "Cherokee (United States)",
		model.LanguageCodeCKB:            "Central Kurdish",
		model.LanguageCodeCKB_IQ:         "Central Kurdish (Iraq)",
		model.LanguageCodeCKB_IR:         "Central Kurdish (Iran)",
		model.LanguageCodeCS:             "Czech",
		model.LanguageCodeCS_CZ:          "Czech (Czechia)",
		model.LanguageCodeCU:             "Church Slavic",
		model.LanguageCodeCU_RU:          "Church Slavic (Russia)",
		model.LanguageCodeCY:             "Welsh",
		model.LanguageCodeCY_GB:          "Welsh (United Kingdom)",
		model.LanguageCodeDA:             "Danish",
		model.LanguageCodeDA_DK:          "Danish (Denmark)",
		model.LanguageCodeDA_GL:          "Danish (Greenland)",
		model.LanguageCodeDAV:            "Taita",
		model.LanguageCodeDAV_KE:         "Taita (Kenya)",
		model.LanguageCodeDE:             "German",
		model.LanguageCodeDE_AT:          "German (Austria)",
		model.LanguageCodeDE_BE:          "German (Belgium)",
		model.LanguageCodeDE_CH:          "German (Switzerland)",
		model.LanguageCodeDE_DE:          "German (Germany)",
		model.LanguageCodeDE_IT:          "German (Italy)",
		model.LanguageCodeDE_LI:          "German (Liechtenstein)",
		model.LanguageCodeDE_LU:          "German (Luxembourg)",
		model.LanguageCodeDJE:            "Zarma",
		model.LanguageCodeDJE_NE:         "Zarma (Niger)",
		model.LanguageCodeDSB:            "Lower Sorbian",
		model.LanguageCodeDSB_DE:         "Lower Sorbian (Germany)",
		model.LanguageCodeDUA:            "Duala",
		model.LanguageCodeDUA_CM:         "Duala (Cameroon)",
		model.LanguageCodeDYO:            "Jola-Fonyi",
		model.LanguageCodeDYO_SN:         "Jola-Fonyi (Senegal)",
		model.LanguageCodeDZ:             "Dzongkha",
		model.LanguageCodeDZ_BT:          "Dzongkha (Bhutan)",
		model.LanguageCodeEBU:            "Embu",
		model.LanguageCodeEBU_KE:         "Embu (Kenya)",
		model.LanguageCodeEE:             "Ewe",
		model.LanguageCodeEE_GH:          "Ewe (Ghana)",
		model.LanguageCodeEE_TG:          "Ewe (Togo)",
		model.LanguageCodeEL:             "Greek",
		model.LanguageCodeEL_CY:          "Greek (Cyprus)",
		model.LanguageCodeEL_GR:          "Greek (Greece)",
		model.LanguageCodeEN:             "English",
		model.LanguageCodeEN_AE:          "English (United Arab Emirates)",
		model.LanguageCodeEN_AG:          "English (Antigua & Barbuda)",
		model.LanguageCodeEN_AI:          "English (Anguilla)",
		model.LanguageCodeEN_AS:          "English (American Samoa)",
		model.LanguageCodeEN_AT:          "English (Austria)",
		model.LanguageCodeEN_AU:          "English (Australia)",
		model.LanguageCodeEN_BB:          "English (Barbados)",
		model.LanguageCodeEN_BE:          "English (Belgium)",
		model.LanguageCodeEN_BI:          "English (Burundi)",
		model.LanguageCodeEN_BM:          "English (Bermuda)",
		model.LanguageCodeEN_BS:          "English (Bahamas)",
		model.LanguageCodeEN_BW:          "English (Botswana)",
		model.LanguageCodeEN_BZ:          "English (Belize)",
		model.LanguageCodeEN_CA:          "English (Canada)",
		model.LanguageCodeEN_CC:          "English (Cocos (Keeling) Islands)",
		model.LanguageCodeEN_CH:          "English (Switzerland)",
		model.LanguageCodeEN_CK:          "English (Cook Islands)",
		model.LanguageCodeEN_CM:          "English (Cameroon)",
		model.LanguageCodeEN_CX:          "English (Christmas Island)",
		model.LanguageCodeEN_CY:          "English (Cyprus)",
		model.LanguageCodeEN_DE:          "English (Germany)",
		model.LanguageCodeEN_DG:          "English (Diego Garcia)",
		model.LanguageCodeEN_DK:          "English (Denmark)",
		model.LanguageCodeEN_DM:          "English (Dominica)",
		model.LanguageCodeEN_ER:          "English (Eritrea)",
		model.LanguageCodeEN_FI:          "English (Finland)",
		model.LanguageCodeEN_FJ:          "English (Fiji)",
		model.LanguageCodeEN_FK:          "English (Falkland Islands)",
		model.LanguageCodeEN_FM:          "English (Micronesia)",
		model.LanguageCodeEN_GB:          "English (United Kingdom)",
		model.LanguageCodeEN_GD:          "English (Grenada)",
		model.LanguageCodeEN_GG:          "English (Guernsey)",
		model.LanguageCodeEN_GH:          "English (Ghana)",
		model.LanguageCodeEN_GI:          "English (Gibraltar)",
		model.LanguageCodeEN_GM:          "English (Gambia)",
		model.LanguageCodeEN_GU:          "English (Guam)",
		model.LanguageCodeEN_GY:          "English (Guyana)",
		model.LanguageCodeEN_HK:          "English (Hong Kong SAR China)",
		model.LanguageCodeEN_IE:          "English (Ireland)",
		model.LanguageCodeEN_IL:          "English (Israel)",
		model.LanguageCodeEN_IM:          "English (Isle of Man)",
		model.LanguageCodeEN_IN:          "English (India)",
		model.LanguageCodeEN_IO:          "English (British Indian Ocean Territory)",
		model.LanguageCodeEN_JE:          "English (Jersey)",
		model.LanguageCodeEN_JM:          "English (Jamaica)",
		model.LanguageCodeEN_KE:          "English (Kenya)",
		model.LanguageCodeEN_KI:          "English (Kiribati)",
		model.LanguageCodeEN_KN:          "English (St. Kitts & Nevis)",
		model.LanguageCodeEN_KY:          "English (Cayman Islands)",
		model.LanguageCodeEN_LC:          "English (St. Lucia)",
		model.LanguageCodeEN_LR:          "English (Liberia)",
		model.LanguageCodeEN_LS:          "English (Lesotho)",
		model.LanguageCodeEN_MG:          "English (Madagascar)",
		model.LanguageCodeEN_MH:          "English (Marshall Islands)",
		model.LanguageCodeEN_MO:          "English (Macao SAR China)",
		model.LanguageCodeEN_MP:          "English (Northern Mariana Islands)",
		model.LanguageCodeEN_MS:          "English (Montserrat)",
		model.LanguageCodeEN_MT:          "English (Malta)",
		model.LanguageCodeEN_MU:          "English (Mauritius)",
		model.LanguageCodeEN_MW:          "English (Malawi)",
		model.LanguageCodeEN_MY:          "English (Malaysia)",
		model.LanguageCodeEN_NA:          "English (Namibia)",
		model.LanguageCodeEN_NF:          "English (Norfolk Island)",
		model.LanguageCodeEN_NG:          "English (Nigeria)",
		model.LanguageCodeEN_NL:          "English (Netherlands)",
		model.LanguageCodeEN_NR:          "English (Nauru)",
		model.LanguageCodeEN_NU:          "English (Niue)",
		model.LanguageCodeEN_NZ:          "English (New Zealand)",
		model.LanguageCodeEN_PG:          "English (Papua New Guinea)",
		model.LanguageCodeEN_PH:          "English (Philippines)",
		model.LanguageCodeEN_PK:          "English (Pakistan)",
		model.LanguageCodeEN_PN:          "English (Pitcairn Islands)",
		model.LanguageCodeEN_PR:          "English (Puerto Rico)",
		model.LanguageCodeEN_PW:          "English (Palau)",
		model.LanguageCodeEN_RW:          "English (Rwanda)",
		model.LanguageCodeEN_SB:          "English (Solomon Islands)",
		model.LanguageCodeEN_SC:          "English (Seychelles)",
		model.LanguageCodeEN_SD:          "English (Sudan)",
		model.LanguageCodeEN_SE:          "English (Sweden)",
		model.LanguageCodeEN_SG:          "English (Singapore)",
		model.LanguageCodeEN_SH:          "English (St. Helena)",
		model.LanguageCodeEN_SI:          "English (Slovenia)",
		model.LanguageCodeEN_SL:          "English (Sierra Leone)",
		model.LanguageCodeEN_SS:          "English (South Sudan)",
		model.LanguageCodeEN_SX:          "English (Sint Maarten)",
		model.LanguageCodeEN_SZ:          "English (Eswatini)",
		model.LanguageCodeEN_TC:          "English (Turks & Caicos Islands)",
		model.LanguageCodeEN_TK:          "English (Tokelau)",
		model.LanguageCodeEN_TO:          "English (Tonga)",
		model.LanguageCodeEN_TT:          "English (Trinidad & Tobago)",
		model.LanguageCodeEN_TV:          "English (Tuvalu)",
		model.LanguageCodeEN_TZ:          "English (Tanzania)",
		model.LanguageCodeEN_UG:          "English (Uganda)",
		model.LanguageCodeEN_UM:          "English (U.S. Outlying Islands)",
		model.LanguageCodeEN_US:          "English (United States)",
		model.LanguageCodeEN_VC:          "English (St. Vincent & Grenadines)",
		model.LanguageCodeEN_VG:          "English (British Virgin Islands)",
		model.LanguageCodeEN_VI:          "English (U.S. Virgin Islands)",
		model.LanguageCodeEN_VU:          "English (Vanuatu)",
		model.LanguageCodeEN_WS:          "English (Samoa)",
		model.LanguageCodeEN_ZA:          "English (South Africa)",
		model.LanguageCodeEN_ZM:          "English (Zambia)",
		model.LanguageCodeEN_ZW:          "English (Zimbabwe)",
		model.LanguageCodeEO:             "Esperanto",
		model.LanguageCodeES:             "Spanish",
		model.LanguageCodeES_AR:          "Spanish (Argentina)",
		model.LanguageCodeES_BO:          "Spanish (Bolivia)",
		model.LanguageCodeES_BR:          "Spanish (Brazil)",
		model.LanguageCodeES_BZ:          "Spanish (Belize)",
		model.LanguageCodeES_CL:          "Spanish (Chile)",
		model.LanguageCodeES_CO:          "Spanish (Colombia)",
		model.LanguageCodeES_CR:          "Spanish (Costa Rica)",
		model.LanguageCodeES_CU:          "Spanish (Cuba)",
		model.LanguageCodeES_DO:          "Spanish (Dominican Republic)",
		model.LanguageCodeES_EA:          "Spanish (Ceuta & Melilla)",
		model.LanguageCodeES_EC:          "Spanish (Ecuador)",
		model.LanguageCodeES_ES:          "Spanish (Spain)",
		model.LanguageCodeES_GQ:          "Spanish (Equatorial Guinea)",
		model.LanguageCodeES_GT:          "Spanish (Guatemala)",
		model.LanguageCodeES_HN:          "Spanish (Honduras)",
		model.LanguageCodeES_IC:          "Spanish (Canary Islands)",
		model.LanguageCodeES_MX:          "Spanish (Mexico)",
		model.LanguageCodeES_NI:          "Spanish (Nicaragua)",
		model.LanguageCodeES_PA:          "Spanish (Panama)",
		model.LanguageCodeES_PE:          "Spanish (Peru)",
		model.LanguageCodeES_PH:          "Spanish (Philippines)",
		model.LanguageCodeES_PR:          "Spanish (Puerto Rico)",
		model.LanguageCodeES_PY:          "Spanish (Paraguay)",
		model.LanguageCodeES_SV:          "Spanish (El Salvador)",
		model.LanguageCodeES_US:          "Spanish (United States)",
		model.LanguageCodeES_UY:          "Spanish (Uruguay)",
		model.LanguageCodeES_VE:          "Spanish (Venezuela)",
		model.LanguageCodeET:             "Estonian",
		model.LanguageCodeET_EE:          "Estonian (Estonia)",
		model.LanguageCodeEU:             "Basque",
		model.LanguageCodeEU_ES:          "Basque (Spain)",
		model.LanguageCodeEWO:            "Ewondo",
		model.LanguageCodeEWO_CM:         "Ewondo (Cameroon)",
		model.LanguageCodeFA:             "Persian",
		model.LanguageCodeFA_AF:          "Persian (Afghanistan)",
		model.LanguageCodeFA_IR:          "Persian (Iran)",
		model.LanguageCodeFF:             "Fulah",
		model.LanguageCodeFF_ADLM:        "Fulah (Adlam)",
		model.LanguageCodeFF_ADLM_BF:     "Fulah (Adlam, Burkina Faso)",
		model.LanguageCodeFF_ADLM_CM:     "Fulah (Adlam, Cameroon)",
		model.LanguageCodeFF_ADLM_GH:     "Fulah (Adlam, Ghana)",
		model.LanguageCodeFF_ADLM_GM:     "Fulah (Adlam, Gambia)",
		model.LanguageCodeFF_ADLM_GN:     "Fulah (Adlam, Guinea)",
		model.LanguageCodeFF_ADLM_GW:     "Fulah (Adlam, Guinea-Bissau)",
		model.LanguageCodeFF_ADLM_LR:     "Fulah (Adlam, Liberia)",
		model.LanguageCodeFF_ADLM_MR:     "Fulah (Adlam, Mauritania)",
		model.LanguageCodeFF_ADLM_NE:     "Fulah (Adlam, Niger)",
		model.LanguageCodeFF_ADLM_NG:     "Fulah (Adlam, Nigeria)",
		model.LanguageCodeFF_ADLM_SL:     "Fulah (Adlam, Sierra Leone)",
		model.LanguageCodeFF_ADLM_SN:     "Fulah (Adlam, Senegal)",
		model.LanguageCodeFF_LATN:        "Fulah (Latin)",
		model.LanguageCodeFF_LATN_BF:     "Fulah (Latin, Burkina Faso)",
		model.LanguageCodeFF_LATN_CM:     "Fulah (Latin, Cameroon)",
		model.LanguageCodeFF_LATN_GH:     "Fulah (Latin, Ghana)",
		model.LanguageCodeFF_LATN_GM:     "Fulah (Latin, Gambia)",
		model.LanguageCodeFF_LATN_GN:     "Fulah (Latin, Guinea)",
		model.LanguageCodeFF_LATN_GW:     "Fulah (Latin, Guinea-Bissau)",
		model.LanguageCodeFF_LATN_LR:     "Fulah (Latin, Liberia)",
		model.LanguageCodeFF_LATN_MR:     "Fulah (Latin, Mauritania)",
		model.LanguageCodeFF_LATN_NE:     "Fulah (Latin, Niger)",
		model.LanguageCodeFF_LATN_NG:     "Fulah (Latin, Nigeria)",
		model.LanguageCodeFF_LATN_SL:     "Fulah (Latin, Sierra Leone)",
		model.LanguageCodeFF_LATN_SN:     "Fulah (Latin, Senegal)",
		model.LanguageCodeFI:             "Finnish",
		model.LanguageCodeFI_FI:          "Finnish (Finland)",
		model.LanguageCodeFIL:            "Filipino",
		model.LanguageCodeFIL_PH:         "Filipino (Philippines)",
		model.LanguageCodeFO:             "Faroese",
		model.LanguageCodeFO_DK:          "Faroese (Denmark)",
		model.LanguageCodeFO_FO:          "Faroese (Faroe Islands)",
		model.LanguageCodeFR:             "French",
		model.LanguageCodeFR_BE:          "French (Belgium)",
		model.LanguageCodeFR_BF:          "French (Burkina Faso)",
		model.LanguageCodeFR_BI:          "French (Burundi)",
		model.LanguageCodeFR_BJ:          "French (Benin)",
		model.LanguageCodeFR_BL:          "French (St. Barthélemy)",
		model.LanguageCodeFR_CA:          "French (Canada)",
		model.LanguageCodeFR_CD:          "French (Congo - Kinshasa)",
		model.LanguageCodeFR_CF:          "French (Central African Republic)",
		model.LanguageCodeFR_CG:          "French (Congo - Brazzaville)",
		model.LanguageCodeFR_CH:          "French (Switzerland)",
		model.LanguageCodeFR_CI:          "French (Côte d’Ivoire)",
		model.LanguageCodeFR_CM:          "French (Cameroon)",
		model.LanguageCodeFR_DJ:          "French (Djibouti)",
		model.LanguageCodeFR_DZ:          "French (Algeria)",
		model.LanguageCodeFR_FR:          "French (France)",
		model.LanguageCodeFR_GA:          "French (Gabon)",
		model.LanguageCodeFR_GF:          "French (French Guiana)",
		model.LanguageCodeFR_GN:          "French (Guinea)",
		model.LanguageCodeFR_GP:          "French (Guadeloupe)",
		model.LanguageCodeFR_GQ:          "French (Equatorial Guinea)",
		model.LanguageCodeFR_HT:          "French (Haiti)",
		model.LanguageCodeFR_KM:          "French (Comoros)",
		model.LanguageCodeFR_LU:          "French (Luxembourg)",
		model.LanguageCodeFR_MA:          "French (Morocco)",
		model.LanguageCodeFR_MC:          "French (Monaco)",
		model.LanguageCodeFR_MF:          "French (St. Martin)",
		model.LanguageCodeFR_MG:          "French (Madagascar)",
		model.LanguageCodeFR_ML:          "French (Mali)",
		model.LanguageCodeFR_MQ:          "French (Martinique)",
		model.LanguageCodeFR_MR:          "French (Mauritania)",
		model.LanguageCodeFR_MU:          "French (Mauritius)",
		model.LanguageCodeFR_NC:          "French (New Caledonia)",
		model.LanguageCodeFR_NE:          "French (Niger)",
		model.LanguageCodeFR_PF:          "French (French Polynesia)",
		model.LanguageCodeFR_PM:          "French (St. Pierre & Miquelon)",
		model.LanguageCodeFR_RE:          "French (Réunion)",
		model.LanguageCodeFR_RW:          "French (Rwanda)",
		model.LanguageCodeFR_SC:          "French (Seychelles)",
		model.LanguageCodeFR_SN:          "French (Senegal)",
		model.LanguageCodeFR_SY:          "French (Syria)",
		model.LanguageCodeFR_TD:          "French (Chad)",
		model.LanguageCodeFR_TG:          "French (Togo)",
		model.LanguageCodeFR_TN:          "French (Tunisia)",
		model.LanguageCodeFR_VU:          "French (Vanuatu)",
		model.LanguageCodeFR_WF:          "French (Wallis & Futuna)",
		model.LanguageCodeFR_YT:          "French (Mayotte)",
		model.LanguageCodeFUR:            "Friulian",
		model.LanguageCodeFUR_IT:         "Friulian (Italy)",
		model.LanguageCodeFY:             "Western Frisian",
		model.LanguageCodeFY_NL:          "Western Frisian (Netherlands)",
		model.LanguageCodeGA:             "Irish",
		model.LanguageCodeGA_GB:          "Irish (United Kingdom)",
		model.LanguageCodeGA_IE:          "Irish (Ireland)",
		model.LanguageCodeGD:             "Scottish Gaelic",
		model.LanguageCodeGD_GB:          "Scottish Gaelic (United Kingdom)",
		model.LanguageCodeGL:             "Galician",
		model.LanguageCodeGL_ES:          "Galician (Spain)",
		model.LanguageCodeGSW:            "Swiss German",
		model.LanguageCodeGSW_CH:         "Swiss German (Switzerland)",
		model.LanguageCodeGSW_FR:         "Swiss German (France)",
		model.LanguageCodeGSW_LI:         "Swiss German (Liechtenstein)",
		model.LanguageCodeGU:             "Gujarati",
		model.LanguageCodeGU_IN:          "Gujarati (India)",
		model.LanguageCodeGUZ:            "Gusii",
		model.LanguageCodeGUZ_KE:         "Gusii (Kenya)",
		model.LanguageCodeGV:             "Manx",
		model.LanguageCodeGV_IM:          "Manx (Isle of Man)",
		model.LanguageCodeHA:             "Hausa",
		model.LanguageCodeHA_GH:          "Hausa (Ghana)",
		model.LanguageCodeHA_NE:          "Hausa (Niger)",
		model.LanguageCodeHA_NG:          "Hausa (Nigeria)",
		model.LanguageCodeHAW:            "Hawaiian",
		model.LanguageCodeHAW_US:         "Hawaiian (United States)",
		model.LanguageCodeHE:             "Hebrew",
		model.LanguageCodeHE_IL:          "Hebrew (Israel)",
		model.LanguageCodeHI:             "Hindi",
		model.LanguageCodeHI_IN:          "Hindi (India)",
		model.LanguageCodeHR:             "Croatian",
		model.LanguageCodeHR_BA:          "Croatian (Bosnia & Herzegovina)",
		model.LanguageCodeHR_HR:          "Croatian (Croatia)",
		model.LanguageCodeHSB:            "Upper Sorbian",
		model.LanguageCodeHSB_DE:         "Upper Sorbian (Germany)",
		model.LanguageCodeHU:             "Hungarian",
		model.LanguageCodeHU_HU:          "Hungarian (Hungary)",
		model.LanguageCodeHY:             "Armenian",
		model.LanguageCodeHY_AM:          "Armenian (Armenia)",
		model.LanguageCodeIA:             "Interlingua",
		model.LanguageCodeID:             "Indonesian",
		model.LanguageCodeID_ID:          "Indonesian (Indonesia)",
		model.LanguageCodeIG:             "Igbo",
		model.LanguageCodeIG_NG:          "Igbo (Nigeria)",
		model.LanguageCodeII:             "Sichuan Yi",
		model.LanguageCodeII_CN:          "Sichuan Yi (China)",
		model.LanguageCodeIS:             "Icelandic",
		model.LanguageCodeIS_IS:          "Icelandic (Iceland)",
		model.LanguageCodeIT:             "Italian",
		model.LanguageCodeIT_CH:          "Italian (Switzerland)",
		model.LanguageCodeIT_IT:          "Italian (Italy)",
		model.LanguageCodeIT_SM:          "Italian (San Marino)",
		model.LanguageCodeIT_VA:          "Italian (Vatican City)",
		model.LanguageCodeJA:             "Japanese",
		model.LanguageCodeJA_JP:          "Japanese (Japan)",
		model.LanguageCodeJGO:            "Ngomba",
		model.LanguageCodeJGO_CM:         "Ngomba (Cameroon)",
		model.LanguageCodeJMC:            "Machame",
		model.LanguageCodeJMC_TZ:         "Machame (Tanzania)",
		model.LanguageCodeJV:             "Javanese",
		model.LanguageCodeJV_ID:          "Javanese (Indonesia)",
		model.LanguageCodeKA:             "Georgian",
		model.LanguageCodeKA_GE:          "Georgian (Georgia)",
		model.LanguageCodeKAB:            "Kabyle",
		model.LanguageCodeKAB_DZ:         "Kabyle (Algeria)",
		model.LanguageCodeKAM:            "Kamba",
		model.LanguageCodeKAM_KE:         "Kamba (Kenya)",
		model.LanguageCodeKDE:            "Makonde",
		model.LanguageCodeKDE_TZ:         "Makonde (Tanzania)",
		model.LanguageCodeKEA:            "Kabuverdianu",
		model.LanguageCodeKEA_CV:         "Kabuverdianu (Cape Verde)",
		model.LanguageCodeKHQ:            "Koyra Chiini",
		model.LanguageCodeKHQ_ML:         "Koyra Chiini (Mali)",
		model.LanguageCodeKI:             "Kikuyu",
		model.LanguageCodeKI_KE:          "Kikuyu (Kenya)",
		model.LanguageCodeKK:             "Kazakh",
		model.LanguageCodeKK_KZ:          "Kazakh (Kazakhstan)",
		model.LanguageCodeKKJ:            "Kako",
		model.LanguageCodeKKJ_CM:         "Kako (Cameroon)",
		model.LanguageCodeKL:             "Kalaallisut",
		model.LanguageCodeKL_GL:          "Kalaallisut (Greenland)",
		model.LanguageCodeKLN:            "Kalenjin",
		model.LanguageCodeKLN_KE:         "Kalenjin (Kenya)",
		model.LanguageCodeKM:             "Khmer",
		model.LanguageCodeKM_KH:          "Khmer (Cambodia)",
		model.LanguageCodeKN:             "Kannada",
		model.LanguageCodeKN_IN:          "Kannada (India)",
		model.LanguageCodeKO:             "Korean",
		model.LanguageCodeKO_KP:          "Korean (North Korea)",
		model.LanguageCodeKO_KR:          "Korean (South Korea)",
		model.LanguageCodeKOK:            "Konkani",
		model.LanguageCodeKOK_IN:         "Konkani (India)",
		model.LanguageCodeKS:             "Kashmiri",
		model.LanguageCodeKS_ARAB:        "Kashmiri (Arabic)",
		model.LanguageCodeKS_ARAB_IN:     "Kashmiri (Arabic, India)",
		model.LanguageCodeKSB:            "Shambala",
		model.LanguageCodeKSB_TZ:         "Shambala (Tanzania)",
		model.LanguageCodeKSF:            "Bafia",
		model.LanguageCodeKSF_CM:         "Bafia (Cameroon)",
		model.LanguageCodeKSH:            "Colognian",
		model.LanguageCodeKSH_DE:         "Colognian (Germany)",
		model.LanguageCodeKU:             "Kurdish",
		model.LanguageCodeKU_TR:          "Kurdish (Turkey)",
		model.LanguageCodeKW:             "Cornish",
		model.LanguageCodeKW_GB:          "Cornish (United Kingdom)",
		model.LanguageCodeKY:             "Kyrgyz",
		model.LanguageCodeKY_KG:          "Kyrgyz (Kyrgyzstan)",
		model.LanguageCodeLAG:            "Langi",
		model.LanguageCodeLAG_TZ:         "Langi (Tanzania)",
		model.LanguageCodeLB:             "Luxembourgish",
		model.LanguageCodeLB_LU:          "Luxembourgish (Luxembourg)",
		model.LanguageCodeLG:             "Ganda",
		model.LanguageCodeLG_UG:          "Ganda (Uganda)",
		model.LanguageCodeLKT:            "Lakota",
		model.LanguageCodeLKT_US:         "Lakota (United States)",
		model.LanguageCodeLN:             "Lingala",
		model.LanguageCodeLN_AO:          "Lingala (Angola)",
		model.LanguageCodeLN_CD:          "Lingala (Congo - Kinshasa)",
		model.LanguageCodeLN_CF:          "Lingala (Central African Republic)",
		model.LanguageCodeLN_CG:          "Lingala (Congo - Brazzaville)",
		model.LanguageCodeLO:             "Lao",
		model.LanguageCodeLO_LA:          "Lao (Laos)",
		model.LanguageCodeLRC:            "Northern Luri",
		model.LanguageCodeLRC_IQ:         "Northern Luri (Iraq)",
		model.LanguageCodeLRC_IR:         "Northern Luri (Iran)",
		model.LanguageCodeLT:             "Lithuanian",
		model.LanguageCodeLT_LT:          "Lithuanian (Lithuania)",
		model.LanguageCodeLU:             "Luba-Katanga",
		model.LanguageCodeLU_CD:          "Luba-Katanga (Congo - Kinshasa)",
		model.LanguageCodeLUO:            "Luo",
		model.LanguageCodeLUO_KE:         "Luo (Kenya)",
		model.LanguageCodeLUY:            "Luyia",
		model.LanguageCodeLUY_KE:         "Luyia (Kenya)",
		model.LanguageCodeLV:             "Latvian",
		model.LanguageCodeLV_LV:          "Latvian (Latvia)",
		model.LanguageCodeMAI:            "Maithili",
		model.LanguageCodeMAI_IN:         "Maithili (India)",
		model.LanguageCodeMAS:            "Masai",
		model.LanguageCodeMAS_KE:         "Masai (Kenya)",
		model.LanguageCodeMAS_TZ:         "Masai (Tanzania)",
		model.LanguageCodeMER:            "Meru",
		model.LanguageCodeMER_KE:         "Meru (Kenya)",
		model.LanguageCodeMFE:            "Morisyen",
		model.LanguageCodeMFE_MU:         "Morisyen (Mauritius)",
		model.LanguageCodeMG:             "Malagasy",
		model.LanguageCodeMG_MG:          "Malagasy (Madagascar)",
		model.LanguageCodeMGH:            "Makhuwa-Meetto",
		model.LanguageCodeMGH_MZ:         "Makhuwa-Meetto (Mozambique)",
		model.LanguageCodeMGO:            "Metaʼ",
		model.LanguageCodeMGO_CM:         "Metaʼ (Cameroon)",
		model.LanguageCodeMI:             "Maori",
		model.LanguageCodeMI_NZ:          "Maori (New Zealand)",
		model.LanguageCodeMK:             "Macedonian",
		model.LanguageCodeMK_MK:          "Macedonian (North Macedonia)",
		model.LanguageCodeML:             "Malayalam",
		model.LanguageCodeML_IN:          "Malayalam (India)",
		model.LanguageCodeMN:             "Mongolian",
		model.LanguageCodeMN_MN:          "Mongolian (Mongolia)",
		model.LanguageCodeMNI:            "Manipuri",
		model.LanguageCodeMNI_BENG:       "Manipuri (Bangla)",
		model.LanguageCodeMNI_BENG_IN:    "Manipuri (Bangla, India)",
		model.LanguageCodeMR:             "Marathi",
		model.LanguageCodeMR_IN:          "Marathi (India)",
		model.LanguageCodeMS:             "Malay",
		model.LanguageCodeMS_BN:          "Malay (Brunei)",
		model.LanguageCodeMS_ID:          "Malay (Indonesia)",
		model.LanguageCodeMS_MY:          "Malay (Malaysia)",
		model.LanguageCodeMS_SG:          "Malay (Singapore)",
		model.LanguageCodeMT:             "Maltese",
		model.LanguageCodeMT_MT:          "Maltese (Malta)",
		model.LanguageCodeMUA:            "Mundang",
		model.LanguageCodeMUA_CM:         "Mundang (Cameroon)",
		model.LanguageCodeMY:             "Burmese",
		model.LanguageCodeMY_MM:          "Burmese (Myanmar (Burma))",
		model.LanguageCodeMZN:            "Mazanderani",
		model.LanguageCodeMZN_IR:         "Mazanderani (Iran)",
		model.LanguageCodeNAQ:            "Nama",
		model.LanguageCodeNAQ_NA:         "Nama (Namibia)",
		model.LanguageCodeNB:             "Norwegian Bokmål",
		model.LanguageCodeNB_NO:          "Norwegian Bokmål (Norway)",
		model.LanguageCodeNB_SJ:          "Norwegian Bokmål (Svalbard & Jan Mayen)",
		model.LanguageCodeND:             "North Ndebele",
		model.LanguageCodeND_ZW:          "North Ndebele (Zimbabwe)",
		model.LanguageCodeNDS:            "Low German",
		model.LanguageCodeNDS_DE:         "Low German (Germany)",
		model.LanguageCodeNDS_NL:         "Low German (Netherlands)",
		model.LanguageCodeNE:             "Nepali",
		model.LanguageCodeNE_IN:          "Nepali (India)",
		model.LanguageCodeNE_NP:          "Nepali (Nepal)",
		model.LanguageCodeNL:             "Dutch",
		model.LanguageCodeNL_AW:          "Dutch (Aruba)",
		model.LanguageCodeNL_BE:          "Dutch (Belgium)",
		model.LanguageCodeNL_BQ:          "Dutch (Caribbean Netherlands)",
		model.LanguageCodeNL_CW:          "Dutch (Curaçao)",
		model.LanguageCodeNL_NL:          "Dutch (Netherlands)",
		model.LanguageCodeNL_SR:          "Dutch (Suriname)",
		model.LanguageCodeNL_SX:          "Dutch (Sint Maarten)",
		model.LanguageCodeNMG:            "Kwasio",
		model.LanguageCodeNMG_CM:         "Kwasio (Cameroon)",
		model.LanguageCodeNN:             "Norwegian Nynorsk",
		model.LanguageCodeNN_NO:          "Norwegian Nynorsk (Norway)",
		model.LanguageCodeNNH:            "Ngiemboon",
		model.LanguageCodeNNH_CM:         "Ngiemboon (Cameroon)",
		model.LanguageCodeNUS:            "Nuer",
		model.LanguageCodeNUS_SS:         "Nuer (South Sudan)",
		model.LanguageCodeNYN:            "Nyankole",
		model.LanguageCodeNYN_UG:         "Nyankole (Uganda)",
		model.LanguageCodeOM:             "Oromo",
		model.LanguageCodeOM_ET:          "Oromo (Ethiopia)",
		model.LanguageCodeOM_KE:          "Oromo (Kenya)",
		model.LanguageCodeOR:             "Odia",
		model.LanguageCodeOR_IN:          "Odia (India)",
		model.LanguageCodeOS:             "Ossetic",
		model.LanguageCodeOS_GE:          "Ossetic (Georgia)",
		model.LanguageCodeOS_RU:          "Ossetic (Russia)",
		model.LanguageCodePA:             "Punjabi",
		model.LanguageCodePA_ARAB:        "Punjabi (Arabic)",
		model.LanguageCodePA_ARAB_PK:     "Punjabi (Arabic, Pakistan)",
		model.LanguageCodePA_GURU:        "Punjabi (Gurmukhi)",
		model.LanguageCodePA_GURU_IN:     "Punjabi (Gurmukhi, India)",
		model.LanguageCodePCM:            "Nigerian Pidgin",
		model.LanguageCodePCM_NG:         "Nigerian Pidgin (Nigeria)",
		model.LanguageCodePL:             "Polish",
		model.LanguageCodePL_PL:          "Polish (Poland)",
		model.LanguageCodePRG:            "Prussian",
		model.LanguageCodePS:             "Pashto",
		model.LanguageCodePS_AF:          "Pashto (Afghanistan)",
		model.LanguageCodePS_PK:          "Pashto (Pakistan)",
		model.LanguageCodePT:             "Portuguese",
		model.LanguageCodePT_AO:          "Portuguese (Angola)",
		model.LanguageCodePT_BR:          "Portuguese (Brazil)",
		model.LanguageCodePT_CH:          "Portuguese (Switzerland)",
		model.LanguageCodePT_CV:          "Portuguese (Cape Verde)",
		model.LanguageCodePT_GQ:          "Portuguese (Equatorial Guinea)",
		model.LanguageCodePT_GW:          "Portuguese (Guinea-Bissau)",
		model.LanguageCodePT_LU:          "Portuguese (Luxembourg)",
		model.LanguageCodePT_MO:          "Portuguese (Macao SAR China)",
		model.LanguageCodePT_MZ:          "Portuguese (Mozambique)",
		model.LanguageCodePT_PT:          "Portuguese (Portugal)",
		model.LanguageCodePT_ST:          "Portuguese (São Tomé & Príncipe)",
		model.LanguageCodePT_TL:          "Portuguese (Timor-Leste)",
		model.LanguageCodeQU:             "Quechua",
		model.LanguageCodeQU_BO:          "Quechua (Bolivia)",
		model.LanguageCodeQU_EC:          "Quechua (Ecuador)",
		model.LanguageCodeQU_PE:          "Quechua (Peru)",
		model.LanguageCodeRM:             "Romansh",
		model.LanguageCodeRM_CH:          "Romansh (Switzerland)",
		model.LanguageCodeRN:             "Rundi",
		model.LanguageCodeRN_BI:          "Rundi (Burundi)",
		model.LanguageCodeRO:             "Romanian",
		model.LanguageCodeRO_MD:          "Romanian (Moldova)",
		model.LanguageCodeRO_RO:          "Romanian (Romania)",
		model.LanguageCodeROF:            "Rombo",
		model.LanguageCodeROF_TZ:         "Rombo (Tanzania)",
		model.LanguageCodeRU:             "Russian",
		model.LanguageCodeRU_BY:          "Russian (Belarus)",
		model.LanguageCodeRU_KG:          "Russian (Kyrgyzstan)",
		model.LanguageCodeRU_KZ:          "Russian (Kazakhstan)",
		model.LanguageCodeRU_MD:          "Russian (Moldova)",
		model.LanguageCodeRU_RU:          "Russian (Russia)",
		model.LanguageCodeRU_UA:          "Russian (Ukraine)",
		model.LanguageCodeRW:             "Kinyarwanda",
		model.LanguageCodeRW_RW:          "Kinyarwanda (Rwanda)",
		model.LanguageCodeRWK:            "Rwa",
		model.LanguageCodeRWK_TZ:         "Rwa (Tanzania)",
		model.LanguageCodeSAH:            "Sakha",
		model.LanguageCodeSAH_RU:         "Sakha (Russia)",
		model.LanguageCodeSAQ:            "Samburu",
		model.LanguageCodeSAQ_KE:         "Samburu (Kenya)",
		model.LanguageCodeSAT:            "Santali",
		model.LanguageCodeSAT_OLCK:       "Santali (Ol Chiki)",
		model.LanguageCodeSAT_OLCK_IN:    "Santali (Ol Chiki, India)",
		model.LanguageCodeSBP:            "Sangu",
		model.LanguageCodeSBP_TZ:         "Sangu (Tanzania)",
		model.LanguageCodeSD:             "Sindhi",
		model.LanguageCodeSD_ARAB:        "Sindhi (Arabic)",
		model.LanguageCodeSD_ARAB_PK:     "Sindhi (Arabic, Pakistan)",
		model.LanguageCodeSD_DEVA:        "Sindhi (Devanagari)",
		model.LanguageCodeSD_DEVA_IN:     "Sindhi (Devanagari, India)",
		model.LanguageCodeSE:             "Northern Sami",
		model.LanguageCodeSE_FI:          "Northern Sami (Finland)",
		model.LanguageCodeSE_NO:          "Northern Sami (Norway)",
		model.LanguageCodeSE_SE:          "Northern Sami (Sweden)",
		model.LanguageCodeSEH:            "Sena",
		model.LanguageCodeSEH_MZ:         "Sena (Mozambique)",
		model.LanguageCodeSES:            "Koyraboro Senni",
		model.LanguageCodeSES_ML:         "Koyraboro Senni (Mali)",
		model.LanguageCodeSG:             "Sango",
		model.LanguageCodeSG_CF:          "Sango (Central African Republic)",
		model.LanguageCodeSHI:            "Tachelhit",
		model.LanguageCodeSHI_LATN:       "Tachelhit (Latin)",
		model.LanguageCodeSHI_LATN_MA:    "Tachelhit (Latin, Morocco)",
		model.LanguageCodeSHI_TFNG:       "Tachelhit (Tifinagh)",
		model.LanguageCodeSHI_TFNG_MA:    "Tachelhit (Tifinagh, Morocco)",
		model.LanguageCodeSI:             "Sinhala",
		model.LanguageCodeSI_LK:          "Sinhala (Sri Lanka)",
		model.LanguageCodeSK:             "Slovak",
		model.LanguageCodeSK_SK:          "Slovak (Slovakia)",
		model.LanguageCodeSL:             "Slovenian",
		model.LanguageCodeSL_SI:          "Slovenian (Slovenia)",
		model.LanguageCodeSMN:            "Inari Sami",
		model.LanguageCodeSMN_FI:         "Inari Sami (Finland)",
		model.LanguageCodeSN:             "Shona",
		model.LanguageCodeSN_ZW:          "Shona (Zimbabwe)",
		model.LanguageCodeSO:             "Somali",
		model.LanguageCodeSO_DJ:          "Somali (Djibouti)",
		model.LanguageCodeSO_ET:          "Somali (Ethiopia)",
		model.LanguageCodeSO_KE:          "Somali (Kenya)",
		model.LanguageCodeSO_SO:          "Somali (Somalia)",
		model.LanguageCodeSQ:             "Albanian",
		model.LanguageCodeSQ_AL:          "Albanian (Albania)",
		model.LanguageCodeSQ_MK:          "Albanian (North Macedonia)",
		model.LanguageCodeSQ_XK:          "Albanian (Kosovo)",
		model.LanguageCodeSR:             "Serbian",
		model.LanguageCodeSR_CYRL:        "Serbian (Cyrillic)",
		model.LanguageCodeSR_CYRL_BA:     "Serbian (Cyrillic, Bosnia & Herzegovina)",
		model.LanguageCodeSR_CYRL_ME:     "Serbian (Cyrillic, Montenegro)",
		model.LanguageCodeSR_CYRL_RS:     "Serbian (Cyrillic, Serbia)",
		model.LanguageCodeSR_CYRL_XK:     "Serbian (Cyrillic, Kosovo)",
		model.LanguageCodeSR_LATN:        "Serbian (Latin)",
		model.LanguageCodeSR_LATN_BA:     "Serbian (Latin, Bosnia & Herzegovina)",
		model.LanguageCodeSR_LATN_ME:     "Serbian (Latin, Montenegro)",
		model.LanguageCodeSR_LATN_RS:     "Serbian (Latin, Serbia)",
		model.LanguageCodeSR_LATN_XK:     "Serbian (Latin, Kosovo)",
		model.LanguageCodeSU:             "Sundanese",
		model.LanguageCodeSU_LATN:        "Sundanese (Latin)",
		model.LanguageCodeSU_LATN_ID:     "Sundanese (Latin, Indonesia)",
		model.LanguageCodeSV:             "Swedish",
		model.LanguageCodeSV_AX:          "Swedish (Åland Islands)",
		model.LanguageCodeSV_FI:          "Swedish (Finland)",
		model.LanguageCodeSV_SE:          "Swedish (Sweden)",
		model.LanguageCodeSW:             "Swahili",
		model.LanguageCodeSW_CD:          "Swahili (Congo - Kinshasa)",
		model.LanguageCodeSW_KE:          "Swahili (Kenya)",
		model.LanguageCodeSW_TZ:          "Swahili (Tanzania)",
		model.LanguageCodeSW_UG:          "Swahili (Uganda)",
		model.LanguageCodeTA:             "Tamil",
		model.LanguageCodeTA_IN:          "Tamil (India)",
		model.LanguageCodeTA_LK:          "Tamil (Sri Lanka)",
		model.LanguageCodeTA_MY:          "Tamil (Malaysia)",
		model.LanguageCodeTA_SG:          "Tamil (Singapore)",
		model.LanguageCodeTE:             "Telugu",
		model.LanguageCodeTE_IN:          "Telugu (India)",
		model.LanguageCodeTEO:            "Teso",
		model.LanguageCodeTEO_KE:         "Teso (Kenya)",
		model.LanguageCodeTEO_UG:         "Teso (Uganda)",
		model.LanguageCodeTG:             "Tajik",
		model.LanguageCodeTG_TJ:          "Tajik (Tajikistan)",
		model.LanguageCodeTH:             "Thai",
		model.LanguageCodeTH_TH:          "Thai (Thailand)",
		model.LanguageCodeTI:             "Tigrinya",
		model.LanguageCodeTI_ER:          "Tigrinya (Eritrea)",
		model.LanguageCodeTI_ET:          "Tigrinya (Ethiopia)",
		model.LanguageCodeTK:             "Turkmen",
		model.LanguageCodeTK_TM:          "Turkmen (Turkmenistan)",
		model.LanguageCodeTO:             "Tongan",
		model.LanguageCodeTO_TO:          "Tongan (Tonga)",
		model.LanguageCodeTR:             "Turkish",
		model.LanguageCodeTR_CY:          "Turkish (Cyprus)",
		model.LanguageCodeTR_TR:          "Turkish (Turkey)",
		model.LanguageCodeTT:             "Tatar",
		model.LanguageCodeTT_RU:          "Tatar (Russia)",
		model.LanguageCodeTWQ:            "Tasawaq",
		model.LanguageCodeTWQ_NE:         "Tasawaq (Niger)",
		model.LanguageCodeTZM:            "Central Atlas Tamazight",
		model.LanguageCodeTZM_MA:         "Central Atlas Tamazight (Morocco)",
		model.LanguageCodeUG:             "Uyghur",
		model.LanguageCodeUG_CN:          "Uyghur (China)",
		model.LanguageCodeUK:             "Ukrainian",
		model.LanguageCodeUK_UA:          "Ukrainian (Ukraine)",
		model.LanguageCodeUR:             "Urdu",
		model.LanguageCodeUR_IN:          "Urdu (India)",
		model.LanguageCodeUR_PK:          "Urdu (Pakistan)",
		model.LanguageCodeUZ:             "Uzbek",
		model.LanguageCodeUZ_ARAB:        "Uzbek (Arabic)",
		model.LanguageCodeUZ_ARAB_AF:     "Uzbek (Arabic, Afghanistan)",
		model.LanguageCodeUZ_CYRL:        "Uzbek (Cyrillic)",
		model.LanguageCodeUZ_CYRL_UZ:     "Uzbek (Cyrillic, Uzbekistan)",
		model.LanguageCodeUZ_LATN:        "Uzbek (Latin)",
		model.LanguageCodeUZ_LATN_UZ:     "Uzbek (Latin, Uzbekistan)",
		model.LanguageCodeVAI:            "Vai",
		model.LanguageCodeVAI_LATN:       "Vai (Latin)",
		model.LanguageCodeVAI_LATN_LR:    "Vai (Latin, Liberia)",
		model.LanguageCodeVAI_VAII:       "Vai (Vai)",
		model.LanguageCodeVAI_VAII_LR:    "Vai (Vai, Liberia)",
		model.LanguageCodeVI:             "Vietnamese",
		model.LanguageCodeVI_VN:          "Vietnamese (Vietnam)",
		model.LanguageCodeVO:             "Volapük",
		model.LanguageCodeVUN:            "Vunjo",
		model.LanguageCodeVUN_TZ:         "Vunjo (Tanzania)",
		model.LanguageCodeWAE:            "Walser",
		model.LanguageCodeWAE_CH:         "Walser (Switzerland)",
		model.LanguageCodeWO:             "Wolof",
		model.LanguageCodeWO_SN:          "Wolof (Senegal)",
		model.LanguageCodeXH:             "Xhosa",
		model.LanguageCodeXH_ZA:          "Xhosa (South Africa)",
		model.LanguageCodeXOG:            "Soga",
		model.LanguageCodeXOG_UG:         "Soga (Uganda)",
		model.LanguageCodeYAV:            "Yangben",
		model.LanguageCodeYAV_CM:         "Yangben (Cameroon)",
		model.LanguageCodeYI:             "Yiddish",
		model.LanguageCodeYO:             "Yoruba",
		model.LanguageCodeYO_BJ:          "Yoruba (Benin)",
		model.LanguageCodeYO_NG:          "Yoruba (Nigeria)",
		model.LanguageCodeYUE:            "Cantonese",
		model.LanguageCodeYUE_HANS:       "Cantonese (Simplified)",
		model.LanguageCodeYUE_HANS_CN:    "Cantonese (Simplified, China)",
		model.LanguageCodeYUE_HANT:       "Cantonese (Traditional)",
		model.LanguageCodeYUE_HANT_HK:    "Cantonese (Traditional, Hong Kong SAR China)",
		model.LanguageCodeZGH:            "Standard Moroccan Tamazight",
		model.LanguageCodeZGH_MA:         "Standard Moroccan Tamazight (Morocco)",
		model.LanguageCodeZH:             "Chinese",
		model.LanguageCodeZH_HANS:        "Chinese (Simplified)",
		model.LanguageCodeZH_HANS_CN:     "Chinese (Simplified, China)",
		model.LanguageCodeZH_HANS_HK:     "Chinese (Simplified, Hong Kong SAR China)",
		model.LanguageCodeZH_HANS_MO:     "Chinese (Simplified, Macao SAR China)",
		model.LanguageCodeZH_HANS_SG:     "Chinese (Simplified, Singapore)",
		model.LanguageCodeZH_HANT:        "Chinese (Traditional)",
		model.LanguageCodeZH_HANT_HK:     "Chinese (Traditional, Hong Kong SAR China)",
		model.LanguageCodeZH_HANT_MO:     "Chinese (Traditional, Macao SAR China)",
		model.LanguageCodeZH_HANT_TW:     "Chinese (Traditional, Taiwan)",
		model.LanguageCodeZU:             "Zulu",
		model.LanguageCodeZU_ZA:          "Zulu (South Africa)",
	}
	RestrictedUsernames = map[string]bool{
		"all":      true,
		"channel":  true,
		"sitename": true,
		"system":   true,
		"admin":    true,
	}

	allCountryCodes := model.AllCountryCode()
	for _, code := range allCountryCodes {
		MULTIPLE_COUNTRIES_MAX_LENGTH += len(code)
	}
	MULTIPLE_COUNTRIES_MAX_LENGTH += len(allCountryCodes) - 1
}

// TaxType is for unifying tax type object that comes from tax gateway
type TaxType struct {
	Code         string
	Descriptiton string
}
