package model_helper

import (
	"crypto/sha1"
	"net/http"
	"regexp"
	"strings"

	"github.com/google/uuid"
	"github.com/samber/lo"
	"github.com/sitename/sitename/model"
)

// constants for access http(s) requests's headers
const (
	HeaderRequestId          = "X-Request-ID"
	HeaderVersionId          = "X-Version-ID"
	HeaderClusterId          = "X-Cluster-ID"
	HeaderAcceptEncoding     = "Accept-Encoding"
	HeaderAcceptLanguage     = "Accept-Language"
	HeaderUserAgent          = "User-Agent"
	HeaderRemoteAddress      = "Remote Address"
	HeaderEtagServer         = "ETag"
	HeaderEtagClient         = "If-None-Match"
	HeaderForwarded          = "X-Forwarded-For"
	HeaderRealIp             = "X-Real-IP"
	HeaderForwardedProto     = "X-Forwarded-Proto"
	HeaderToken              = "token"
	HeaderCsrfToken          = "X-CSRF-Token"
	HeaderBearer             = "BEARER"
	HeaderAuth               = "Authorization"
	HeaderCloudToken         = "X-Cloud-Token"
	HeaderRemoteClusterToken = "X-RemoteCluster-Token"
	HeaderRemoteClusterId    = "X-RemoteCluster-Id"
	HeaderRequestedWith      = "X-Requested-With"
	HeaderRequestedWith_XML  = "XMLHttpRequest"
	HeaderRange              = "Range"
	STATUS                   = "status"
	STATUS_OK                = "OK"
	STATUS_FAIL              = "FAIL"
	STATUS_UNHEALTHY         = "UNHEALTHY"
	STATUS_REMOVE            = "REMOVE"
	CLIENT_DIR               = "client"
)

var UUID_NAMESPACE = uuid.New()

// Refer to https://github.com/nu7hatch/gouuid/blob/179d4d0c4d8d407a32af483c2354df1d2c91e6c3/uuid.go#L113 for details
func NewUUIDv5(nameSpace *uuid.UUID, name []byte) uuid.UUID {
	u := new(uuid.UUID)

	hash := sha1.New()
	hash.Write(nameSpace[:])
	hash.Write(name)
	copy(u[:], hash.Sum([]byte{})[:16])
	u[8] = (u[8] | 0x40) & 0x7F
	u[6] = (u[6] & 0xF) | (5 << 4)

	return *u
}

func GetClientId(r *http.Request) uuid.UUID {
	headers := []string{HeaderAcceptEncoding, HeaderAcceptLanguage, HeaderUserAgent, HeaderForwarded, HeaderRemoteAddress}
	headers = lo.Map(headers, func(item string, _ int) string {
		return r.Header.Get(item)
	})
	name := strings.Join(headers, "_")
	return NewUUIDv5(&UUID_NAMESPACE, []byte(name))
}

type TimePeriodType string

// time period types
const (
	DAY   TimePeriodType = "day"
	WEEK  TimePeriodType = "week"
	MONTH TimePeriodType = "month"
	YEAR  TimePeriodType = "year"
)

func (t TimePeriodType) IsValid() bool {
	switch t {
	case DAY, WEEK, MONTH, YEAR:
		return true
	default:
		return false
	}
}

const (
	ProductNotPublishedAppErrID       = "app.checkout.product_unpublished.app_error"
	InvalidArgumentAppErrorID         = "app.invalid_arguments.app_error" // InvalidArgumentAppErrorID used when creating app errors on invalid argument
	ErrorCalculatingMoneyErrorID      = "app.error_calculating_money.app_error"
	ErrorCreatingTransactionErrorID   = "app.error_creating_transaction.app_error"
	ErrorCommittingTransactionErrorID = "app.error_committing_transaction.app_error"
	ErrorCalculatingMeasurementID     = "app.error_calculating_measurement.app_error"
	ErrorMarshallingDataID            = "app.error_marshalling_data.app_error"
	ErrorUnMarshallingDataID          = "app.error_unmarshalling_data.app_error"
)

// some default values for model fields
const (
	TimeZone                       = "UTC"
	USER_AUTH_SERVICE_EMAIL        = "email"
	DEFAULT_CURRENCY               = model.CurrencyUSD
	USER_NAME_MAX_LENGTH           = 64
	USER_EMAIL_MAX_LENGTH          = 128
	USER_NAME_MIN_LENGTH           = 1
	CURRENCY_CODE_MAX_LENGTH       = 3
	LANGUAGE_CODE_MAX_LENGTH       = 5
	WEIGHT_UNIT_MAX_LENGTH         = 5
	URL_LINK_MAX_LENGTH            = 200
	SINGLE_COUNTRY_CODE_MAX_LENGTH = 5
	IP_ADDRESS_MAX_LENGTH          = 39
	DEFAULT_LOCALE                 = model.LanguageCodeEN // this is default language also
	DEFAULT_COUNTRY                = model.CountryCodeUS
)

var (
	// Countries                     map[model.Countrycode]string  // countries supported by app
	// Languages                     map[model.Languagecode]string // Languages supported by app
	MULTIPLE_COUNTRIES_MAX_LENGTH int // some model"s country fields contains multiple countries

	ValidUsernameChars  = regexp.MustCompile(`^[a-z0-9\.\-_]+$`) // regexp for username validation
	RestrictedUsernames map[string]bool                          // usernames that cannot be used

	// usernames that can only be used by system
	ReservedName = []string{
		"admin",
		"api",
		"channel",
		"claim",
		"error",
		"files",
		"help",
		"landing",
		"login",
		"mfa",
		"oauth",
		"plug",
		"plugins",
		"post",
		"signup",
		"sitename",
	}
)

// initConsts is called by init() function that located in /model/init.go
func initConsts() {
	// borrowed from django_countries
	// Countries = map[model.Countrycode]string{
	// 	model.CountrycodeAF: "Afghanistan",
	// 	model.CountryCodeAx: "Aland Islands",
	// 	model.CountryCodeAl: "Albania",
	// 	model.CountryCodeDz: "Algeria",
	// 	model.CountryCodeAs: "American Samoa",
	// 	model.CountryCodeAd: "Andorra",
	// 	model.CountryCodeAo: "Angola",
	// 	model.CountryCodeAi: "Anguilla",
	// 	model.CountryCodeAq: "Antarctica",
	// 	model.CountryCodeAg: "Antigua and Barbuda",
	// 	model.CountryCodeAr: "Argentina",
	// 	model.CountryCodeAm: "Armenia",
	// 	model.CountryCodeAw: "Aruba",
	// 	model.CountryCodeAu: "Australia",
	// 	model.CountryCodeAt: "Austria",
	// 	model.CountryCodeAz: "Azerbaijan",
	// 	model.CountryCodeBs: "Bahamas",
	// 	model.CountryCodeBh: "Bahrain",
	// 	model.CountryCodeBd: "Bangladesh",
	// 	model.CountryCodeBb: "Barbados",
	// 	model.CountryCodeBy: "Belarus",
	// 	model.CountryCodeBe: "Belgium",
	// 	model.CountryCodeBz: "Belize",
	// 	model.CountryCodeBj: "Benin",
	// 	model.CountryCodeBm: "Bermuda",
	// 	model.CountryCodeBt: "Bhutan",
	// 	model.CountryCodeBo: "Bolivia",
	// 	model.CountryCodeBq: "Bonaire, Sint Eustatius and Saba",
	// 	model.CountryCodeBa: "Bosnia and Herzegovina",
	// 	model.CountryCodeBw: "Botswana",
	// 	model.CountryCodeBv: "Bouvet Island",
	// 	model.CountryCodeBr: "Brazil",
	// 	model.CountryCodeIo: "British Indian Ocean Territory",
	// 	model.CountryCodeBn: "Brunei",
	// 	model.CountryCodeBg: "Bulgaria",
	// 	model.CountryCodeBf: "Burkina Faso",
	// 	model.CountryCodeBi: "Burundi",
	// 	model.CountryCodeCv: "Cabo Verde",
	// 	model.CountryCodeKh: "Cambodia",
	// 	model.CountryCodeCm: "Cameroon",
	// 	model.CountryCodeCa: "Canada",
	// 	model.CountryCodeKy: "Cayman Islands",
	// 	model.CountryCodeCf: "Central African Republic",
	// 	model.CountryCodeTd: "Chad",
	// 	model.CountryCodeCl: "Chile",
	// 	model.CountryCodeCn: "China",
	// 	model.CountryCodeCx: "Christmas Island",
	// 	model.CountryCodeCc: "Cocos (Keeling) Islands",
	// 	model.CountryCodeCo: "Colombia",
	// 	model.CountryCodeKm: "Comoros",
	// 	model.CountryCodeCg: "Congo",
	// 	model.CountryCodeCd: "Congo (the Democratic Republic of the)",
	// 	model.CountryCodeCk: "Cook Islands",
	// 	model.CountryCodeCr: "Costa Rica",
	// 	model.CountryCodeCi: "C\u00f4te d'Ivoire",
	// 	model.CountryCodeHr: "Croatia",
	// 	model.CountryCodeCu: "Cuba",
	// 	model.CountryCodeCw: "Cura\u00e7ao",
	// 	model.CountryCodeCy: "Cyprus",
	// 	model.CountryCodeCz: "Czechia",
	// 	model.CountryCodeDk: "Denmark",
	// 	model.CountryCodeDj: "Djibouti",
	// 	model.CountryCodeDm: "Dominica",
	// 	model.CountryCodeDo: "Dominican Republic",
	// 	model.CountryCodeEc: "Ecuador",
	// 	model.CountryCodeEg: "Egypt",
	// 	model.CountryCodeSv: "El Salvador",
	// 	model.CountryCodeGq: "Equatorial Guinea",
	// 	model.CountryCodeEr: "Eritrea",
	// 	model.CountryCodeEe: "Estonia",
	// 	model.CountryCodeSz: "Eswatini",
	// 	model.CountryCodeEt: "Ethiopia",
	// 	model.CountryCodeFk: "Falkland Islands (Malvinas)",
	// 	model.CountryCodeFo: "Faroe Islands",
	// 	model.CountryCodeFj: "Fiji",
	// 	model.CountryCodeFi: "Finland",
	// 	model.CountryCodeFr: "France",
	// 	model.CountryCodeGf: "French Guiana",
	// 	model.CountryCodePf: "French Polynesia",
	// 	model.CountryCodeTf: "French Southern Territories",
	// 	model.CountryCodeGa: "Gabon",
	// 	model.CountryCodeGm: "Gambia",
	// 	model.CountryCodeGe: "Georgia",
	// 	model.CountryCodeDe: "Germany",
	// 	model.CountryCodeGh: "Ghana",
	// 	model.CountryCodeGi: "Gibraltar",
	// 	model.CountryCodeGr: "Greece",
	// 	model.CountryCodeGl: "Greenland",
	// 	model.CountryCodeGd: "Grenada",
	// 	model.CountryCodeGp: "Guadeloupe",
	// 	model.CountryCodeGu: "Guam",
	// 	model.CountryCodeGt: "Guatemala",
	// 	model.CountryCodeGg: "Guernsey",
	// 	model.CountryCodeGn: "Guinea",
	// 	model.CountryCodeGw: "Guinea-Bissau",
	// 	model.CountryCodeGy: "Guyana",
	// 	model.CountryCodeHt: "Haiti",
	// 	model.CountryCodeHm: "Heard Island and McDonald Islands",
	// 	model.CountryCodeVa: "Holy See",
	// 	model.CountryCodeHn: "Honduras",
	// 	model.CountryCodeHk: "Hong Kong",
	// 	model.CountryCodeHu: "Hungary",
	// 	model.CountryCodeIs: "Iceland",
	// 	model.CountryCodeIn: "India",
	// 	model.CountryCodeId: "Indonesia",
	// 	model.CountryCodeIr: "Iran",
	// 	model.CountryCodeIq: "Iraq",
	// 	model.CountryCodeIe: "Ireland",
	// 	model.CountryCodeIm: "Isle of Man",
	// 	model.CountryCodeIl: "Israel",
	// 	model.CountryCodeIt: "Italy",
	// 	model.CountryCodeJm: "Jamaica",
	// 	model.CountryCodeJp: "Japan",
	// 	model.CountryCodeJe: "Jersey",
	// 	model.CountryCodeJo: "Jordan",
	// 	model.CountryCodeKz: "Kazakhstan",
	// 	model.CountryCodeKe: "Kenya",
	// 	model.CountryCodeKi: "Kiribati",
	// 	model.CountryCodeKp: "North Korea",
	// 	model.CountryCodeKr: "South Korea",
	// 	model.CountryCodeKw: "Kuwait",
	// 	model.CountryCodeKg: "Kyrgyzstan",
	// 	model.CountryCodeLa: "Laos",
	// 	model.CountryCodeLv: "Latvia",
	// 	model.CountryCodeLb: "Lebanon",
	// 	model.CountryCodeLs: "Lesotho",
	// 	model.CountryCodeLr: "Liberia",
	// 	model.CountryCodeLy: "Libya",
	// 	model.CountryCodeLi: "Liechtenstein",
	// 	model.CountryCodeLt: "Lithuania",
	// 	model.CountryCodeLu: "Luxembourg",
	// 	model.CountryCodeMo: "Macao",
	// 	model.CountryCodeMg: "Madagascar",
	// 	model.CountryCodeMw: "Malawi",
	// 	model.CountryCodeMy: "Malaysia",
	// 	model.CountryCodeMv: "Maldives",
	// 	model.CountryCodeMl: "Mali",
	// 	model.CountryCodeMt: "Malta",
	// 	model.CountryCodeMh: "Marshall Islands",
	// 	model.CountryCodeMq: "Martinique",
	// 	model.CountryCodeMr: "Mauritania",
	// 	model.CountryCodeMu: "Mauritius",
	// 	model.CountryCodeYt: "Mayotte",
	// 	model.CountryCodeMx: "Mexico",
	// 	model.CountryCodeFm: "Micronesia (Federated States of)",
	// 	model.CountryCodeMd: "Moldova",
	// 	model.CountryCodeMc: "Monaco",
	// 	model.CountryCodeMn: "Mongolia",
	// 	model.CountryCodeMe: "Montenegro",
	// 	model.CountryCodeMs: "Montserrat",
	// 	model.CountryCodeMa: "Morocco",
	// 	model.CountryCodeMz: "Mozambique",
	// 	model.CountryCodeMm: "Myanmar",
	// 	model.CountryCodeNa: "Namibia",
	// 	model.CountryCodeNr: "Nauru",
	// 	model.CountryCodeNp: "Nepal",
	// 	model.CountryCodeNl: "Netherlands",
	// 	model.CountryCodeNc: "New Caledonia",
	// 	model.CountryCodeNz: "New Zealand",
	// 	model.CountryCodeNi: "Nicaragua",
	// 	model.CountryCodeNe: "Niger",
	// 	model.CountryCodeNg: "Nigeria",
	// 	model.CountryCodeNu: "Niue",
	// 	model.CountryCodeNf: "Norfolk Island",
	// 	model.CountryCodeMk: "North Macedonia",
	// 	model.CountryCodeMp: "Northern Mariana Islands",
	// 	model.CountryCodeNo: "Norway",
	// 	model.CountryCodeOm: "Oman",
	// 	model.CountryCodePk: "Pakistan",
	// 	model.CountryCodePw: "Palau",
	// 	model.CountryCodePs: "Palestine, State of",
	// 	model.CountryCodePa: "Panama",
	// 	model.CountryCodePg: "Papua New Guinea",
	// 	model.CountryCodePy: "Paraguay",
	// 	model.CountryCodePe: "Peru",
	// 	model.CountryCodePh: "Philippines",
	// 	model.CountryCodePn: "Pitcairn",
	// 	model.CountryCodePl: "Poland",
	// 	model.CountryCodePt: "Portugal",
	// 	model.CountryCodePr: "Puerto Rico",
	// 	model.CountryCodeQa: "Qatar",
	// 	model.CountryCodeRe: "R\u00e9union",
	// 	model.CountryCodeRo: "Romania",
	// 	model.CountryCodeRu: "Russia",
	// 	model.CountryCodeRw: "Rwanda",
	// 	model.CountryCodeBl: "Saint Barth\u00e9lemy",
	// 	model.CountryCodeSh: "Saint Helena, Ascension and Tristan da Cunha",
	// 	model.CountryCodeKn: "Saint Kitts and Nevis",
	// 	model.CountryCodeLc: "Saint Lucia",
	// 	model.CountryCodeMf: "Saint Martin (French part)",
	// 	model.CountryCodePm: "Saint Pierre and Miquelon",
	// 	model.CountryCodeVc: "Saint Vincent and the Grenadines",
	// 	model.CountryCodeWs: "Samoa",
	// 	model.CountryCodeSm: "San Marino",
	// 	model.CountryCodeSt: "Sao Tome and Principe",
	// 	model.CountryCodeSa: "Saudi Arabia",
	// 	model.CountryCodeSn: "Senegal",
	// 	model.CountryCodeRs: "Serbia",
	// 	model.CountryCodeSc: "Seychelles",
	// 	model.CountryCodeSl: "Sierra Leone",
	// 	model.CountryCodeSg: "Singapore",
	// 	model.CountryCodeSx: "Sint Maarten (Dutch part)",
	// 	model.CountryCodeSk: "Slovakia",
	// 	model.CountryCodeSi: "Slovenia",
	// 	model.CountryCodeSb: "Solomon Islands",
	// 	model.CountryCodeSo: "Somalia",
	// 	model.CountryCodeZa: "South Africa",
	// 	model.CountryCodeGs: "South Georgia and the South Sandwich Islands",
	// 	model.CountryCodeSs: "South Sudan",
	// 	model.CountryCodeEs: "Spain",
	// 	model.CountryCodeLk: "Sri Lanka",
	// 	model.CountryCodeSd: "Sudan",
	// 	model.CountryCodeSr: "Suriname",
	// 	model.CountryCodeSj: "Svalbard and Jan Mayen",
	// 	model.CountryCodeSe: "Sweden",
	// 	model.CountryCodeCh: "Switzerland",
	// 	model.CountryCodeSy: "Syria",
	// 	model.CountryCodeTw: "Taiwan",
	// 	model.CountryCodeTj: "Tajikistan",
	// 	model.CountryCodeTz: "Tanzania",
	// 	model.CountryCodeTh: "Thailand",
	// 	model.CountryCodeTl: "Timor-Leste",
	// 	model.CountryCodeTg: "Togo",
	// 	model.CountryCodeTk: "Tokelau",
	// 	model.CountryCodeTo: "Tonga",
	// 	model.CountryCodeTt: "Trinidad and Tobago",
	// 	model.CountryCodeTn: "Tunisia",
	// 	model.CountryCodeTr: "Turkey",
	// 	model.CountryCodeTm: "Turkmenistan",
	// 	model.CountryCodeTc: "Turks and Caicos Islands",
	// 	model.CountryCodeTv: "Tuvalu",
	// 	model.CountryCodeUg: "Uganda",
	// 	model.CountryCodeUa: "Ukraine",
	// 	model.CountryCodeAe: "United Arab Emirates",
	// 	model.CountryCodeGb: "United Kingdom",
	// 	model.CountryCodeUm: "United States Minor Outlying Islands",
	// 	model.CountryCodeUs: "United States of America",
	// 	model.CountryCodeUy: "Uruguay",
	// 	model.CountryCodeUz: "Uzbekistan",
	// 	model.CountryCodeVu: "Vanuatu",
	// 	model.CountryCodeVe: "Venezuela",
	// 	model.CountryCodeVn: "Vietnam",
	// 	model.CountryCodeVg: "Virgin Islands (British)",
	// 	model.CountryCodeVi: "Virgin Islands (U.S.)",
	// 	model.CountryCodeWf: "Wallis and Futuna",
	// 	model.CountryCodeEh: "Western Sahara",
	// 	model.CountryCodeYe: "Yemen",
	// 	model.CountryCodeZm: "Zambia",
	// 	model.CountryCodeZw: "Zimbabwe",
	// 	model.CountryCodeEu: "European Union",
	// }

	// Languages = map[model.Languagecode]string{
	// 	LanguageCodeEnumAf:           "Afrikaans",
	// 	LanguageCodeEnumAfNa:         "Afrikaans (Namibia)",
	// 	LanguageCodeEnumAfZa:         "Afrikaans (South Africa)",
	// 	LanguageCodeEnumAgq:          "Aghem",
	// 	LanguageCodeEnumAgqCm:        "Aghem (Cameroon)",
	// 	LanguageCodeEnumAk:           "Akan",
	// 	LanguageCodeEnumAkGh:         "Akan (Ghana)",
	// 	LanguageCodeEnumAm:           "Amharic",
	// 	LanguageCodeEnumAmEt:         "Amharic (Ethiopia)",
	// 	LanguageCodeEnumAr:           "Arabic",
	// 	LanguageCodeEnumArAe:         "Arabic (United Arab Emirates)",
	// 	LanguageCodeEnumArBh:         "Arabic (Bahrain)",
	// 	LanguageCodeEnumArDj:         "Arabic (Djibouti)",
	// 	LanguageCodeEnumArDz:         "Arabic (Algeria)",
	// 	LanguageCodeEnumArEg:         "Arabic (Egypt)",
	// 	LanguageCodeEnumArEh:         "Arabic (Western Sahara)",
	// 	LanguageCodeEnumArEr:         "Arabic (Eritrea)",
	// 	LanguageCodeEnumArIl:         "Arabic (Israel)",
	// 	LanguageCodeEnumArIq:         "Arabic (Iraq)",
	// 	LanguageCodeEnumArJo:         "Arabic (Jordan)",
	// 	LanguageCodeEnumArKm:         "Arabic (Comoros)",
	// 	LanguageCodeEnumArKw:         "Arabic (Kuwait)",
	// 	LanguageCodeEnumArLb:         "Arabic (Lebanon)",
	// 	LanguageCodeEnumArLy:         "Arabic (Libya)",
	// 	LanguageCodeEnumArMa:         "Arabic (Morocco)",
	// 	LanguageCodeEnumArMr:         "Arabic (Mauritania)",
	// 	LanguageCodeEnumArOm:         "Arabic (Oman)",
	// 	LanguageCodeEnumArPs:         "Arabic (Palestinian Territories)",
	// 	LanguageCodeEnumArQa:         "Arabic (Qatar)",
	// 	LanguageCodeEnumArSa:         "Arabic (Saudi Arabia)",
	// 	LanguageCodeEnumArSd:         "Arabic (Sudan)",
	// 	LanguageCodeEnumArSo:         "Arabic (Somalia)",
	// 	LanguageCodeEnumArSs:         "Arabic (South Sudan)",
	// 	LanguageCodeEnumArSy:         "Arabic (Syria)",
	// 	LanguageCodeEnumArTd:         "Arabic (Chad)",
	// 	LanguageCodeEnumArTn:         "Arabic (Tunisia)",
	// 	LanguageCodeEnumArYe:         "Arabic (Yemen)",
	// 	LanguageCodeEnumAs:           "Assamese",
	// 	LanguageCodeEnumAsIn:         "Assamese (India)",
	// 	LanguageCodeEnumAsa:          "Asu",
	// 	LanguageCodeEnumAsaTz:        "Asu (Tanzania)",
	// 	LanguageCodeEnumAst:          "Asturian",
	// 	LanguageCodeEnumAstEs:        "Asturian (Spain)",
	// 	LanguageCodeEnumAz:           "Azerbaijani",
	// 	LanguageCodeEnumAzCyrl:       "Azerbaijani (Cyrillic)",
	// 	LanguageCodeEnumAzCyrlAz:     "Azerbaijani (Cyrillic, Azerbaijan)",
	// 	LanguageCodeEnumAzLatn:       "Azerbaijani (Latin)",
	// 	LanguageCodeEnumAzLatnAz:     "Azerbaijani (Latin, Azerbaijan)",
	// 	LanguageCodeEnumBas:          "Basaa",
	// 	LanguageCodeEnumBasCm:        "Basaa (Cameroon)",
	// 	LanguageCodeEnumBe:           "Belarusian",
	// 	LanguageCodeEnumBeBy:         "Belarusian (Belarus)",
	// 	LanguageCodeEnumBem:          "Bemba",
	// 	LanguageCodeEnumBemZm:        "Bemba (Zambia)",
	// 	LanguageCodeEnumBez:          "Bena",
	// 	LanguageCodeEnumBezTz:        "Bena (Tanzania)",
	// 	LanguageCodeEnumBg:           "Bulgarian",
	// 	LanguageCodeEnumBgBg:         "Bulgarian (Bulgaria)",
	// 	LanguageCodeEnumBm:           "Bambara",
	// 	LanguageCodeEnumBmMl:         "Bambara (Mali)",
	// 	LanguageCodeEnumBn:           "Bangla",
	// 	LanguageCodeEnumBnBd:         "Bangla (Bangladesh)",
	// 	LanguageCodeEnumBnIn:         "Bangla (India)",
	// 	LanguageCodeEnumBo:           "Tibetan",
	// 	LanguageCodeEnumBoCn:         "Tibetan (China)",
	// 	LanguageCodeEnumBoIn:         "Tibetan (India)",
	// 	LanguageCodeEnumBr:           "Breton",
	// 	LanguageCodeEnumBrFr:         "Breton (France)",
	// 	LanguageCodeEnumBrx:          "Bodo",
	// 	LanguageCodeEnumBrxIn:        "Bodo (India)",
	// 	LanguageCodeEnumBs:           "Bosnian",
	// 	LanguageCodeEnumBsCyrl:       "Bosnian (Cyrillic)",
	// 	LanguageCodeEnumBsCyrlBa:     "Bosnian (Cyrillic, Bosnia & Herzegovina)",
	// 	LanguageCodeEnumBsLatn:       "Bosnian (Latin)",
	// 	LanguageCodeEnumBsLatnBa:     "Bosnian (Latin, Bosnia & Herzegovina)",
	// 	LanguageCodeEnumCa:           "Catalan",
	// 	LanguageCodeEnumCaAd:         "Catalan (Andorra)",
	// 	LanguageCodeEnumCaEs:         "Catalan (Spain)",
	// 	LanguageCodeEnumCaEsValencia: "Catalan (Spain, Valencian)",
	// 	LanguageCodeEnumCaFr:         "Catalan (France)",
	// 	LanguageCodeEnumCaIt:         "Catalan (Italy)",
	// 	LanguageCodeEnumCcp:          "Chakma",
	// 	LanguageCodeEnumCcpBd:        "Chakma (Bangladesh)",
	// 	LanguageCodeEnumCcpIn:        "Chakma (India)",
	// 	LanguageCodeEnumCe:           "Chechen",
	// 	LanguageCodeEnumCeRu:         "Chechen (Russia)",
	// 	LanguageCodeEnumCeb:          "Cebuano",
	// 	LanguageCodeEnumCebPh:        "Cebuano (Philippines)",
	// 	LanguageCodeEnumCgg:          "Chiga",
	// 	LanguageCodeEnumCggUg:        "Chiga (Uganda)",
	// 	LanguageCodeEnumChr:          "Cherokee",
	// 	LanguageCodeEnumChrUs:        "Cherokee (United States)",
	// 	LanguageCodeEnumCkb:          "Central Kurdish",
	// 	LanguageCodeEnumCkbIq:        "Central Kurdish (Iraq)",
	// 	LanguageCodeEnumCkbIr:        "Central Kurdish (Iran)",
	// 	LanguageCodeEnumCs:           "Czech",
	// 	LanguageCodeEnumCsCz:         "Czech (Czechia)",
	// 	LanguageCodeEnumCu:           "Church Slavic",
	// 	LanguageCodeEnumCuRu:         "Church Slavic (Russia)",
	// 	LanguageCodeEnumCy:           "Welsh",
	// 	LanguageCodeEnumCyGb:         "Welsh (United Kingdom)",
	// 	LanguageCodeEnumDa:           "Danish",
	// 	LanguageCodeEnumDaDk:         "Danish (Denmark)",
	// 	LanguageCodeEnumDaGl:         "Danish (Greenland)",
	// 	LanguageCodeEnumDav:          "Taita",
	// 	LanguageCodeEnumDavKe:        "Taita (Kenya)",
	// 	LanguageCodeEnumDe:           "German",
	// 	LanguageCodeEnumDeAt:         "German (Austria)",
	// 	LanguageCodeEnumDeBe:         "German (Belgium)",
	// 	LanguageCodeEnumDeCh:         "German (Switzerland)",
	// 	LanguageCodeEnumDeDe:         "German (Germany)",
	// 	LanguageCodeEnumDeIt:         "German (Italy)",
	// 	LanguageCodeEnumDeLi:         "German (Liechtenstein)",
	// 	LanguageCodeEnumDeLu:         "German (Luxembourg)",
	// 	LanguageCodeEnumDje:          "Zarma",
	// 	LanguageCodeEnumDjeNe:        "Zarma (Niger)",
	// 	LanguageCodeEnumDsb:          "Lower Sorbian",
	// 	LanguageCodeEnumDsbDe:        "Lower Sorbian (Germany)",
	// 	LanguageCodeEnumDua:          "Duala",
	// 	LanguageCodeEnumDuaCm:        "Duala (Cameroon)",
	// 	LanguageCodeEnumDyo:          "Jola-Fonyi",
	// 	LanguageCodeEnumDyoSn:        "Jola-Fonyi (Senegal)",
	// 	LanguageCodeEnumDz:           "Dzongkha",
	// 	LanguageCodeEnumDzBt:         "Dzongkha (Bhutan)",
	// 	LanguageCodeEnumEbu:          "Embu",
	// 	LanguageCodeEnumEbuKe:        "Embu (Kenya)",
	// 	LanguageCodeEnumEe:           "Ewe",
	// 	LanguageCodeEnumEeGh:         "Ewe (Ghana)",
	// 	LanguageCodeEnumEeTg:         "Ewe (Togo)",
	// 	LanguageCodeEnumEl:           "Greek",
	// 	LanguageCodeEnumElCy:         "Greek (Cyprus)",
	// 	LanguageCodeEnumElGr:         "Greek (Greece)",
	// 	LanguageCodeEnumEn:           "English",
	// 	LanguageCodeEnumEnAe:         "English (United Arab Emirates)",
	// 	LanguageCodeEnumEnAg:         "English (Antigua & Barbuda)",
	// 	LanguageCodeEnumEnAi:         "English (Anguilla)",
	// 	LanguageCodeEnumEnAs:         "English (American Samoa)",
	// 	LanguageCodeEnumEnAt:         "English (Austria)",
	// 	LanguageCodeEnumEnAu:         "English (Australia)",
	// 	LanguageCodeEnumEnBb:         "English (Barbados)",
	// 	LanguageCodeEnumEnBe:         "English (Belgium)",
	// 	LanguageCodeEnumEnBi:         "English (Burundi)",
	// 	LanguageCodeEnumEnBm:         "English (Bermuda)",
	// 	LanguageCodeEnumEnBs:         "English (Bahamas)",
	// 	LanguageCodeEnumEnBw:         "English (Botswana)",
	// 	LanguageCodeEnumEnBz:         "English (Belize)",
	// 	LanguageCodeEnumEnCa:         "English (Canada)",
	// 	LanguageCodeEnumEnCc:         "English (Cocos (Keeling) Islands)",
	// 	LanguageCodeEnumEnCh:         "English (Switzerland)",
	// 	LanguageCodeEnumEnCk:         "English (Cook Islands)",
	// 	LanguageCodeEnumEnCm:         "English (Cameroon)",
	// 	LanguageCodeEnumEnCx:         "English (Christmas Island)",
	// 	LanguageCodeEnumEnCy:         "English (Cyprus)",
	// 	LanguageCodeEnumEnDe:         "English (Germany)",
	// 	LanguageCodeEnumEnDg:         "English (Diego Garcia)",
	// 	LanguageCodeEnumEnDk:         "English (Denmark)",
	// 	LanguageCodeEnumEnDm:         "English (Dominica)",
	// 	LanguageCodeEnumEnEr:         "English (Eritrea)",
	// 	LanguageCodeEnumEnFi:         "English (Finland)",
	// 	LanguageCodeEnumEnFj:         "English (Fiji)",
	// 	LanguageCodeEnumEnFk:         "English (Falkland Islands)",
	// 	LanguageCodeEnumEnFm:         "English (Micronesia)",
	// 	LanguageCodeEnumEnGb:         "English (United Kingdom)",
	// 	LanguageCodeEnumEnGd:         "English (Grenada)",
	// 	LanguageCodeEnumEnGg:         "English (Guernsey)",
	// 	LanguageCodeEnumEnGh:         "English (Ghana)",
	// 	LanguageCodeEnumEnGi:         "English (Gibraltar)",
	// 	LanguageCodeEnumEnGm:         "English (Gambia)",
	// 	LanguageCodeEnumEnGu:         "English (Guam)",
	// 	LanguageCodeEnumEnGy:         "English (Guyana)",
	// 	LanguageCodeEnumEnHk:         "English (Hong Kong SAR China)",
	// 	LanguageCodeEnumEnIe:         "English (Ireland)",
	// 	LanguageCodeEnumEnIl:         "English (Israel)",
	// 	LanguageCodeEnumEnIm:         "English (Isle of Man)",
	// 	LanguageCodeEnumEnIn:         "English (India)",
	// 	LanguageCodeEnumEnIo:         "English (British Indian Ocean Territory)",
	// 	LanguageCodeEnumEnJe:         "English (Jersey)",
	// 	LanguageCodeEnumEnJm:         "English (Jamaica)",
	// 	LanguageCodeEnumEnKe:         "English (Kenya)",
	// 	LanguageCodeEnumEnKi:         "English (Kiribati)",
	// 	LanguageCodeEnumEnKn:         "English (St. Kitts & Nevis)",
	// 	LanguageCodeEnumEnKy:         "English (Cayman Islands)",
	// 	LanguageCodeEnumEnLc:         "English (St. Lucia)",
	// 	LanguageCodeEnumEnLr:         "English (Liberia)",
	// 	LanguageCodeEnumEnLs:         "English (Lesotho)",
	// 	LanguageCodeEnumEnMg:         "English (Madagascar)",
	// 	LanguageCodeEnumEnMh:         "English (Marshall Islands)",
	// 	LanguageCodeEnumEnMo:         "English (Macao SAR China)",
	// 	LanguageCodeEnumEnMp:         "English (Northern Mariana Islands)",
	// 	LanguageCodeEnumEnMs:         "English (Montserrat)",
	// 	LanguageCodeEnumEnMt:         "English (Malta)",
	// 	LanguageCodeEnumEnMu:         "English (Mauritius)",
	// 	LanguageCodeEnumEnMw:         "English (Malawi)",
	// 	LanguageCodeEnumEnMy:         "English (Malaysia)",
	// 	LanguageCodeEnumEnNa:         "English (Namibia)",
	// 	LanguageCodeEnumEnNf:         "English (Norfolk Island)",
	// 	LanguageCodeEnumEnNg:         "English (Nigeria)",
	// 	LanguageCodeEnumEnNl:         "English (Netherlands)",
	// 	LanguageCodeEnumEnNr:         "English (Nauru)",
	// 	LanguageCodeEnumEnNu:         "English (Niue)",
	// 	LanguageCodeEnumEnNz:         "English (New Zealand)",
	// 	LanguageCodeEnumEnPg:         "English (Papua New Guinea)",
	// 	LanguageCodeEnumEnPh:         "English (Philippines)",
	// 	LanguageCodeEnumEnPk:         "English (Pakistan)",
	// 	LanguageCodeEnumEnPn:         "English (Pitcairn Islands)",
	// 	LanguageCodeEnumEnPr:         "English (Puerto Rico)",
	// 	LanguageCodeEnumEnPw:         "English (Palau)",
	// 	LanguageCodeEnumEnRw:         "English (Rwanda)",
	// 	LanguageCodeEnumEnSb:         "English (Solomon Islands)",
	// 	LanguageCodeEnumEnSc:         "English (Seychelles)",
	// 	LanguageCodeEnumEnSd:         "English (Sudan)",
	// 	LanguageCodeEnumEnSe:         "English (Sweden)",
	// 	LanguageCodeEnumEnSg:         "English (Singapore)",
	// 	LanguageCodeEnumEnSh:         "English (St. Helena)",
	// 	LanguageCodeEnumEnSi:         "English (Slovenia)",
	// 	LanguageCodeEnumEnSl:         "English (Sierra Leone)",
	// 	LanguageCodeEnumEnSs:         "English (South Sudan)",
	// 	LanguageCodeEnumEnSx:         "English (Sint Maarten)",
	// 	LanguageCodeEnumEnSz:         "English (Eswatini)",
	// 	LanguageCodeEnumEnTc:         "English (Turks & Caicos Islands)",
	// 	LanguageCodeEnumEnTk:         "English (Tokelau)",
	// 	LanguageCodeEnumEnTo:         "English (Tonga)",
	// 	LanguageCodeEnumEnTt:         "English (Trinidad & Tobago)",
	// 	LanguageCodeEnumEnTv:         "English (Tuvalu)",
	// 	LanguageCodeEnumEnTz:         "English (Tanzania)",
	// 	LanguageCodeEnumEnUg:         "English (Uganda)",
	// 	LanguageCodeEnumEnUm:         "English (U.S. Outlying Islands)",
	// 	LanguageCodeEnumEnUs:         "English (United States)",
	// 	LanguageCodeEnumEnVc:         "English (St. Vincent & Grenadines)",
	// 	LanguageCodeEnumEnVg:         "English (British Virgin Islands)",
	// 	LanguageCodeEnumEnVi:         "English (U.S. Virgin Islands)",
	// 	LanguageCodeEnumEnVu:         "English (Vanuatu)",
	// 	LanguageCodeEnumEnWs:         "English (Samoa)",
	// 	LanguageCodeEnumEnZa:         "English (South Africa)",
	// 	LanguageCodeEnumEnZm:         "English (Zambia)",
	// 	LanguageCodeEnumEnZw:         "English (Zimbabwe)",
	// 	LanguageCodeEnumEo:           "Esperanto",
	// 	LanguageCodeEnumEs:           "Spanish",
	// 	LanguageCodeEnumEsAr:         "Spanish (Argentina)",
	// 	LanguageCodeEnumEsBo:         "Spanish (Bolivia)",
	// 	LanguageCodeEnumEsBr:         "Spanish (Brazil)",
	// 	LanguageCodeEnumEsBz:         "Spanish (Belize)",
	// 	LanguageCodeEnumEsCl:         "Spanish (Chile)",
	// 	LanguageCodeEnumEsCo:         "Spanish (Colombia)",
	// 	LanguageCodeEnumEsCr:         "Spanish (Costa Rica)",
	// 	LanguageCodeEnumEsCu:         "Spanish (Cuba)",
	// 	LanguageCodeEnumEsDo:         "Spanish (Dominican Republic)",
	// 	LanguageCodeEnumEsEa:         "Spanish (Ceuta & Melilla)",
	// 	LanguageCodeEnumEsEc:         "Spanish (Ecuador)",
	// 	LanguageCodeEnumEsEs:         "Spanish (Spain)",
	// 	LanguageCodeEnumEsGq:         "Spanish (Equatorial Guinea)",
	// 	LanguageCodeEnumEsGt:         "Spanish (Guatemala)",
	// 	LanguageCodeEnumEsHn:         "Spanish (Honduras)",
	// 	LanguageCodeEnumEsIc:         "Spanish (Canary Islands)",
	// 	LanguageCodeEnumEsMx:         "Spanish (Mexico)",
	// 	LanguageCodeEnumEsNi:         "Spanish (Nicaragua)",
	// 	LanguageCodeEnumEsPa:         "Spanish (Panama)",
	// 	LanguageCodeEnumEsPe:         "Spanish (Peru)",
	// 	LanguageCodeEnumEsPh:         "Spanish (Philippines)",
	// 	LanguageCodeEnumEsPr:         "Spanish (Puerto Rico)",
	// 	LanguageCodeEnumEsPy:         "Spanish (Paraguay)",
	// 	LanguageCodeEnumEsSv:         "Spanish (El Salvador)",
	// 	LanguageCodeEnumEsUs:         "Spanish (United States)",
	// 	LanguageCodeEnumEsUy:         "Spanish (Uruguay)",
	// 	LanguageCodeEnumEsVe:         "Spanish (Venezuela)",
	// 	LanguageCodeEnumEt:           "Estonian",
	// 	LanguageCodeEnumEtEe:         "Estonian (Estonia)",
	// 	LanguageCodeEnumEu:           "Basque",
	// 	LanguageCodeEnumEuEs:         "Basque (Spain)",
	// 	LanguageCodeEnumEwo:          "Ewondo",
	// 	LanguageCodeEnumEwoCm:        "Ewondo (Cameroon)",
	// 	LanguageCodeEnumFa:           "Persian",
	// 	LanguageCodeEnumFaAf:         "Persian (Afghanistan)",
	// 	LanguageCodeEnumFaIr:         "Persian (Iran)",
	// 	LanguageCodeEnumFf:           "Fulah",
	// 	LanguageCodeEnumFfAdlm:       "Fulah (Adlam)",
	// 	LanguageCodeEnumFfAdlmBf:     "Fulah (Adlam, Burkina Faso)",
	// 	LanguageCodeEnumFfAdlmCm:     "Fulah (Adlam, Cameroon)",
	// 	LanguageCodeEnumFfAdlmGh:     "Fulah (Adlam, Ghana)",
	// 	LanguageCodeEnumFfAdlmGm:     "Fulah (Adlam, Gambia)",
	// 	LanguageCodeEnumFfAdlmGn:     "Fulah (Adlam, Guinea)",
	// 	LanguageCodeEnumFfAdlmGw:     "Fulah (Adlam, Guinea-Bissau)",
	// 	LanguageCodeEnumFfAdlmLr:     "Fulah (Adlam, Liberia)",
	// 	LanguageCodeEnumFfAdlmMr:     "Fulah (Adlam, Mauritania)",
	// 	LanguageCodeEnumFfAdlmNe:     "Fulah (Adlam, Niger)",
	// 	LanguageCodeEnumFfAdlmNg:     "Fulah (Adlam, Nigeria)",
	// 	LanguageCodeEnumFfAdlmSl:     "Fulah (Adlam, Sierra Leone)",
	// 	LanguageCodeEnumFfAdlmSn:     "Fulah (Adlam, Senegal)",
	// 	LanguageCodeEnumFfLatn:       "Fulah (Latin)",
	// 	LanguageCodeEnumFfLatnBf:     "Fulah (Latin, Burkina Faso)",
	// 	LanguageCodeEnumFfLatnCm:     "Fulah (Latin, Cameroon)",
	// 	LanguageCodeEnumFfLatnGh:     "Fulah (Latin, Ghana)",
	// 	LanguageCodeEnumFfLatnGm:     "Fulah (Latin, Gambia)",
	// 	LanguageCodeEnumFfLatnGn:     "Fulah (Latin, Guinea)",
	// 	LanguageCodeEnumFfLatnGw:     "Fulah (Latin, Guinea-Bissau)",
	// 	LanguageCodeEnumFfLatnLr:     "Fulah (Latin, Liberia)",
	// 	LanguageCodeEnumFfLatnMr:     "Fulah (Latin, Mauritania)",
	// 	LanguageCodeEnumFfLatnNe:     "Fulah (Latin, Niger)",
	// 	LanguageCodeEnumFfLatnNg:     "Fulah (Latin, Nigeria)",
	// 	LanguageCodeEnumFfLatnSl:     "Fulah (Latin, Sierra Leone)",
	// 	LanguageCodeEnumFfLatnSn:     "Fulah (Latin, Senegal)",
	// 	LanguageCodeEnumFi:           "Finnish",
	// 	LanguageCodeEnumFiFi:         "Finnish (Finland)",
	// 	LanguageCodeEnumFil:          "Filipino",
	// 	LanguageCodeEnumFilPh:        "Filipino (Philippines)",
	// 	LanguageCodeEnumFo:           "Faroese",
	// 	LanguageCodeEnumFoDk:         "Faroese (Denmark)",
	// 	LanguageCodeEnumFoFo:         "Faroese (Faroe Islands)",
	// 	LanguageCodeEnumFr:           "French",
	// 	LanguageCodeEnumFrBe:         "French (Belgium)",
	// 	LanguageCodeEnumFrBf:         "French (Burkina Faso)",
	// 	LanguageCodeEnumFrBi:         "French (Burundi)",
	// 	LanguageCodeEnumFrBj:         "French (Benin)",
	// 	LanguageCodeEnumFrBl:         "French (St. Barth\u00e9lemy)",
	// 	LanguageCodeEnumFrCa:         "French (Canada)",
	// 	LanguageCodeEnumFrCd:         "French (Congo - Kinshasa)",
	// 	LanguageCodeEnumFrCf:         "French (Central African Republic)",
	// 	LanguageCodeEnumFrCg:         "French (Congo - Brazzaville)",
	// 	LanguageCodeEnumFrCh:         "French (Switzerland)",
	// 	LanguageCodeEnumFrCi:         "French (C\u00f4te d\u2019Ivoire)",
	// 	LanguageCodeEnumFrCm:         "French (Cameroon)",
	// 	LanguageCodeEnumFrDj:         "French (Djibouti)",
	// 	LanguageCodeEnumFrDz:         "French (Algeria)",
	// 	LanguageCodeEnumFrFr:         "French (France)",
	// 	LanguageCodeEnumFrGa:         "French (Gabon)",
	// 	LanguageCodeEnumFrGf:         "French (French Guiana)",
	// 	LanguageCodeEnumFrGn:         "French (Guinea)",
	// 	LanguageCodeEnumFrGp:         "French (Guadeloupe)",
	// 	LanguageCodeEnumFrGq:         "French (Equatorial Guinea)",
	// 	LanguageCodeEnumFrHt:         "French (Haiti)",
	// 	LanguageCodeEnumFrKm:         "French (Comoros)",
	// 	LanguageCodeEnumFrLu:         "French (Luxembourg)",
	// 	LanguageCodeEnumFrMa:         "French (Morocco)",
	// 	LanguageCodeEnumFrMc:         "French (Monaco)",
	// 	LanguageCodeEnumFrMf:         "French (St. Martin)",
	// 	LanguageCodeEnumFrMg:         "French (Madagascar)",
	// 	LanguageCodeEnumFrMl:         "French (Mali)",
	// 	LanguageCodeEnumFrMq:         "French (Martinique)",
	// 	LanguageCodeEnumFrMr:         "French (Mauritania)",
	// 	LanguageCodeEnumFrMu:         "French (Mauritius)",
	// 	LanguageCodeEnumFrNc:         "French (New Caledonia)",
	// 	LanguageCodeEnumFrNe:         "French (Niger)",
	// 	LanguageCodeEnumFrPf:         "French (French Polynesia)",
	// 	LanguageCodeEnumFrPm:         "French (St. Pierre & Miquelon)",
	// 	LanguageCodeEnumFrRe:         "French (R\u00e9union)",
	// 	LanguageCodeEnumFrRw:         "French (Rwanda)",
	// 	LanguageCodeEnumFrSc:         "French (Seychelles)",
	// 	LanguageCodeEnumFrSn:         "French (Senegal)",
	// 	LanguageCodeEnumFrSy:         "French (Syria)",
	// 	LanguageCodeEnumFrTd:         "French (Chad)",
	// 	LanguageCodeEnumFrTg:         "French (Togo)",
	// 	LanguageCodeEnumFrTn:         "French (Tunisia)",
	// 	LanguageCodeEnumFrVu:         "French (Vanuatu)",
	// 	LanguageCodeEnumFrWf:         "French (Wallis & Futuna)",
	// 	LanguageCodeEnumFrYt:         "French (Mayotte)",
	// 	LanguageCodeEnumFur:          "Friulian",
	// 	LanguageCodeEnumFurIt:        "Friulian (Italy)",
	// 	LanguageCodeEnumFy:           "Western Frisian",
	// 	LanguageCodeEnumFyNl:         "Western Frisian (Netherlands)",
	// 	LanguageCodeEnumGa:           "Irish",
	// 	LanguageCodeEnumGaGb:         "Irish (United Kingdom)",
	// 	LanguageCodeEnumGaIe:         "Irish (Ireland)",
	// 	LanguageCodeEnumGd:           "Scottish Gaelic",
	// 	LanguageCodeEnumGdGb:         "Scottish Gaelic (United Kingdom)",
	// 	LanguageCodeEnumGl:           "Galician",
	// 	LanguageCodeEnumGlEs:         "Galician (Spain)",
	// 	LanguageCodeEnumGsw:          "Swiss German",
	// 	LanguageCodeEnumGswCh:        "Swiss German (Switzerland)",
	// 	LanguageCodeEnumGswFr:        "Swiss German (France)",
	// 	LanguageCodeEnumGswLi:        "Swiss German (Liechtenstein)",
	// 	LanguageCodeEnumGu:           "Gujarati",
	// 	LanguageCodeEnumGuIn:         "Gujarati (India)",
	// 	LanguageCodeEnumGuz:          "Gusii",
	// 	LanguageCodeEnumGuzKe:        "Gusii (Kenya)",
	// 	LanguageCodeEnumGv:           "Manx",
	// 	LanguageCodeEnumGvIm:         "Manx (Isle of Man)",
	// 	LanguageCodeEnumHa:           "Hausa",
	// 	LanguageCodeEnumHaGh:         "Hausa (Ghana)",
	// 	LanguageCodeEnumHaNe:         "Hausa (Niger)",
	// 	LanguageCodeEnumHaNg:         "Hausa (Nigeria)",
	// 	LanguageCodeEnumHaw:          "Hawaiian",
	// 	LanguageCodeEnumHawUs:        "Hawaiian (United States)",
	// 	LanguageCodeEnumHe:           "Hebrew",
	// 	LanguageCodeEnumHeIl:         "Hebrew (Israel)",
	// 	LanguageCodeEnumHi:           "Hindi",
	// 	LanguageCodeEnumHiIn:         "Hindi (India)",
	// 	LanguageCodeEnumHr:           "Croatian",
	// 	LanguageCodeEnumHrBa:         "Croatian (Bosnia & Herzegovina)",
	// 	LanguageCodeEnumHrHr:         "Croatian (Croatia)",
	// 	LanguageCodeEnumHsb:          "Upper Sorbian",
	// 	LanguageCodeEnumHsbDe:        "Upper Sorbian (Germany)",
	// 	LanguageCodeEnumHu:           "Hungarian",
	// 	LanguageCodeEnumHuHu:         "Hungarian (Hungary)",
	// 	LanguageCodeEnumHy:           "Armenian",
	// 	LanguageCodeEnumHyAm:         "Armenian (Armenia)",
	// 	LanguageCodeEnumIa:           "Interlingua",
	// 	LanguageCodeEnumId:           "Indonesian",
	// 	LanguageCodeEnumIDID:         "Indonesian (Indonesia)",
	// 	LanguageCodeEnumIg:           "Igbo",
	// 	LanguageCodeEnumIgNg:         "Igbo (Nigeria)",
	// 	LanguageCodeEnumIi:           "Sichuan Yi",
	// 	LanguageCodeEnumIiCn:         "Sichuan Yi (China)",
	// 	LanguageCodeEnumIs:           "Icelandic",
	// 	LanguageCodeEnumIsIs:         "Icelandic (Iceland)",
	// 	LanguageCodeEnumIt:           "Italian",
	// 	LanguageCodeEnumItCh:         "Italian (Switzerland)",
	// 	LanguageCodeEnumItIt:         "Italian (Italy)",
	// 	LanguageCodeEnumItSm:         "Italian (San Marino)",
	// 	LanguageCodeEnumItVa:         "Italian (Vatican City)",
	// 	LanguageCodeEnumJa:           "Japanese",
	// 	LanguageCodeEnumJaJp:         "Japanese (Japan)",
	// 	LanguageCodeEnumJgo:          "Ngomba",
	// 	LanguageCodeEnumJgoCm:        "Ngomba (Cameroon)",
	// 	LanguageCodeEnumJmc:          "Machame",
	// 	LanguageCodeEnumJmcTz:        "Machame (Tanzania)",
	// 	LanguageCodeEnumJv:           "Javanese",
	// 	LanguageCodeEnumJvID:         "Javanese (Indonesia)",
	// 	LanguageCodeEnumKa:           "Georgian",
	// 	LanguageCodeEnumKaGe:         "Georgian (Georgia)",
	// 	LanguageCodeEnumKab:          "Kabyle",
	// 	LanguageCodeEnumKabDz:        "Kabyle (Algeria)",
	// 	LanguageCodeEnumKam:          "Kamba",
	// 	LanguageCodeEnumKamKe:        "Kamba (Kenya)",
	// 	LanguageCodeEnumKde:          "Makonde",
	// 	LanguageCodeEnumKdeTz:        "Makonde (Tanzania)",
	// 	LanguageCodeEnumKea:          "Kabuverdianu",
	// 	LanguageCodeEnumKeaCv:        "Kabuverdianu (Cape Verde)",
	// 	LanguageCodeEnumKhq:          "Koyra Chiini",
	// 	LanguageCodeEnumKhqMl:        "Koyra Chiini (Mali)",
	// 	LanguageCodeEnumKi:           "Kikuyu",
	// 	LanguageCodeEnumKiKe:         "Kikuyu (Kenya)",
	// 	LanguageCodeEnumKk:           "Kazakh",
	// 	LanguageCodeEnumKkKz:         "Kazakh (Kazakhstan)",
	// 	LanguageCodeEnumKkj:          "Kako",
	// 	LanguageCodeEnumKkjCm:        "Kako (Cameroon)",
	// 	LanguageCodeEnumKl:           "Kalaallisut",
	// 	LanguageCodeEnumKlGl:         "Kalaallisut (Greenland)",
	// 	LanguageCodeEnumKln:          "Kalenjin",
	// 	LanguageCodeEnumKlnKe:        "Kalenjin (Kenya)",
	// 	LanguageCodeEnumKm:           "Khmer",
	// 	LanguageCodeEnumKmKh:         "Khmer (Cambodia)",
	// 	LanguageCodeEnumKn:           "Kannada",
	// 	LanguageCodeEnumKnIn:         "Kannada (India)",
	// 	LanguageCodeEnumKo:           "Korean",
	// 	LanguageCodeEnumKoKp:         "Korean (North Korea)",
	// 	LanguageCodeEnumKoKr:         "Korean (South Korea)",
	// 	LanguageCodeEnumKok:          "Konkani",
	// 	LanguageCodeEnumKokIn:        "Konkani (India)",
	// 	LanguageCodeEnumKs:           "Kashmiri",
	// 	LanguageCodeEnumKsArab:       "Kashmiri (Arabic)",
	// 	LanguageCodeEnumKsArabIn:     "Kashmiri (Arabic, India)",
	// 	LanguageCodeEnumKsb:          "Shambala",
	// 	LanguageCodeEnumKsbTz:        "Shambala (Tanzania)",
	// 	LanguageCodeEnumKsf:          "Bafia",
	// 	LanguageCodeEnumKsfCm:        "Bafia (Cameroon)",
	// 	LanguageCodeEnumKsh:          "Colognian",
	// 	LanguageCodeEnumKshDe:        "Colognian (Germany)",
	// 	LanguageCodeEnumKu:           "Kurdish",
	// 	LanguageCodeEnumKuTr:         "Kurdish (Turkey)",
	// 	LanguageCodeEnumKw:           "Cornish",
	// 	LanguageCodeEnumKwGb:         "Cornish (United Kingdom)",
	// 	LanguageCodeEnumKy:           "Kyrgyz",
	// 	LanguageCodeEnumKyKg:         "Kyrgyz (Kyrgyzstan)",
	// 	LanguageCodeEnumLag:          "Langi",
	// 	LanguageCodeEnumLagTz:        "Langi (Tanzania)",
	// 	LanguageCodeEnumLb:           "Luxembourgish",
	// 	LanguageCodeEnumLbLu:         "Luxembourgish (Luxembourg)",
	// 	LanguageCodeEnumLg:           "Ganda",
	// 	LanguageCodeEnumLgUg:         "Ganda (Uganda)",
	// 	LanguageCodeEnumLkt:          "Lakota",
	// 	LanguageCodeEnumLktUs:        "Lakota (United States)",
	// 	LanguageCodeEnumLn:           "Lingala",
	// 	LanguageCodeEnumLnAo:         "Lingala (Angola)",
	// 	LanguageCodeEnumLnCd:         "Lingala (Congo - Kinshasa)",
	// 	LanguageCodeEnumLnCf:         "Lingala (Central African Republic)",
	// 	LanguageCodeEnumLnCg:         "Lingala (Congo - Brazzaville)",
	// 	LanguageCodeEnumLo:           "Lao",
	// 	LanguageCodeEnumLoLa:         "Lao (Laos)",
	// 	LanguageCodeEnumLrc:          "Northern Luri",
	// 	LanguageCodeEnumLrcIq:        "Northern Luri (Iraq)",
	// 	LanguageCodeEnumLrcIr:        "Northern Luri (Iran)",
	// 	LanguageCodeEnumLt:           "Lithuanian",
	// 	LanguageCodeEnumLtLt:         "Lithuanian (Lithuania)",
	// 	LanguageCodeEnumLu:           "Luba-Katanga",
	// 	LanguageCodeEnumLuCd:         "Luba-Katanga (Congo - Kinshasa)",
	// 	LanguageCodeEnumLuo:          "Luo",
	// 	LanguageCodeEnumLuoKe:        "Luo (Kenya)",
	// 	LanguageCodeEnumLuy:          "Luyia",
	// 	LanguageCodeEnumLuyKe:        "Luyia (Kenya)",
	// 	LanguageCodeEnumLv:           "Latvian",
	// 	LanguageCodeEnumLvLv:         "Latvian (Latvia)",
	// 	LanguageCodeEnumMai:          "Maithili",
	// 	LanguageCodeEnumMaiIn:        "Maithili (India)",
	// 	LanguageCodeEnumMas:          "Masai",
	// 	LanguageCodeEnumMasKe:        "Masai (Kenya)",
	// 	LanguageCodeEnumMasTz:        "Masai (Tanzania)",
	// 	LanguageCodeEnumMer:          "Meru",
	// 	LanguageCodeEnumMerKe:        "Meru (Kenya)",
	// 	LanguageCodeEnumMfe:          "Morisyen",
	// 	LanguageCodeEnumMfeMu:        "Morisyen (Mauritius)",
	// 	LanguageCodeEnumMg:           "Malagasy",
	// 	LanguageCodeEnumMgMg:         "Malagasy (Madagascar)",
	// 	LanguageCodeEnumMgh:          "Makhuwa-Meetto",
	// 	LanguageCodeEnumMghMz:        "Makhuwa-Meetto (Mozambique)",
	// 	LanguageCodeEnumMgo:          "Meta\u02bc",
	// 	LanguageCodeEnumMgoCm:        "Meta\u02bc (Cameroon)",
	// 	LanguageCodeEnumMi:           "Maori",
	// 	LanguageCodeEnumMiNz:         "Maori (New Zealand)",
	// 	LanguageCodeEnumMk:           "Macedonian",
	// 	LanguageCodeEnumMkMk:         "Macedonian (North Macedonia)",
	// 	LanguageCodeEnumMl:           "Malayalam",
	// 	LanguageCodeEnumMlIn:         "Malayalam (India)",
	// 	LanguageCodeEnumMn:           "Mongolian",
	// 	LanguageCodeEnumMnMn:         "Mongolian (Mongolia)",
	// 	LanguageCodeEnumMni:          "Manipuri",
	// 	LanguageCodeEnumMniBeng:      "Manipuri (Bangla)",
	// 	LanguageCodeEnumMniBengIn:    "Manipuri (Bangla, India)",
	// 	LanguageCodeEnumMr:           "Marathi",
	// 	LanguageCodeEnumMrIn:         "Marathi (India)",
	// 	LanguageCodeEnumMs:           "Malay",
	// 	LanguageCodeEnumMsBn:         "Malay (Brunei)",
	// 	LanguageCodeEnumMsID:         "Malay (Indonesia)",
	// 	LanguageCodeEnumMsMy:         "Malay (Malaysia)",
	// 	LanguageCodeEnumMsSg:         "Malay (Singapore)",
	// 	LanguageCodeEnumMt:           "Maltese",
	// 	LanguageCodeEnumMtMt:         "Maltese (Malta)",
	// 	LanguageCodeEnumMua:          "Mundang",
	// 	LanguageCodeEnumMuaCm:        "Mundang (Cameroon)",
	// 	LanguageCodeEnumMy:           "Burmese",
	// 	LanguageCodeEnumMyMm:         "Burmese (Myanmar (Burma))",
	// 	LanguageCodeEnumMzn:          "Mazanderani",
	// 	LanguageCodeEnumMznIr:        "Mazanderani (Iran)",
	// 	LanguageCodeEnumNaq:          "Nama",
	// 	LanguageCodeEnumNaqNa:        "Nama (Namibia)",
	// 	LanguageCodeEnumNb:           "Norwegian Bokm\u00e5l",
	// 	LanguageCodeEnumNbNo:         "Norwegian Bokm\u00e5l (Norway)",
	// 	LanguageCodeEnumNbSj:         "Norwegian Bokm\u00e5l (Svalbard & Jan Mayen)",
	// 	LanguageCodeEnumNd:           "North Ndebele",
	// 	LanguageCodeEnumNdZw:         "North Ndebele (Zimbabwe)",
	// 	LanguageCodeEnumNds:          "Low German",
	// 	LanguageCodeEnumNdsDe:        "Low German (Germany)",
	// 	LanguageCodeEnumNdsNl:        "Low German (Netherlands)",
	// 	LanguageCodeEnumNe:           "Nepali",
	// 	LanguageCodeEnumNeIn:         "Nepali (India)",
	// 	LanguageCodeEnumNeNp:         "Nepali (Nepal)",
	// 	LanguageCodeEnumNl:           "Dutch",
	// 	LanguageCodeEnumNlAw:         "Dutch (Aruba)",
	// 	LanguageCodeEnumNlBe:         "Dutch (Belgium)",
	// 	LanguageCodeEnumNlBq:         "Dutch (Caribbean Netherlands)",
	// 	LanguageCodeEnumNlCw:         "Dutch (Cura\u00e7ao)",
	// 	LanguageCodeEnumNlNl:         "Dutch (Netherlands)",
	// 	LanguageCodeEnumNlSr:         "Dutch (Suriname)",
	// 	LanguageCodeEnumNlSx:         "Dutch (Sint Maarten)",
	// 	LanguageCodeEnumNmg:          "Kwasio",
	// 	LanguageCodeEnumNmgCm:        "Kwasio (Cameroon)",
	// 	LanguageCodeEnumNn:           "Norwegian Nynorsk",
	// 	LanguageCodeEnumNnNo:         "Norwegian Nynorsk (Norway)",
	// 	LanguageCodeEnumNnh:          "Ngiemboon",
	// 	LanguageCodeEnumNnhCm:        "Ngiemboon (Cameroon)",
	// 	LanguageCodeEnumNus:          "Nuer",
	// 	LanguageCodeEnumNusSs:        "Nuer (South Sudan)",
	// 	LanguageCodeEnumNyn:          "Nyankole",
	// 	LanguageCodeEnumNynUg:        "Nyankole (Uganda)",
	// 	LanguageCodeEnumOm:           "Oromo",
	// 	LanguageCodeEnumOmEt:         "Oromo (Ethiopia)",
	// 	LanguageCodeEnumOmKe:         "Oromo (Kenya)",
	// 	LanguageCodeEnumOr:           "Odia",
	// 	LanguageCodeEnumOrIn:         "Odia (India)",
	// 	LanguageCodeEnumOs:           "Ossetic",
	// 	LanguageCodeEnumOsGe:         "Ossetic (Georgia)",
	// 	LanguageCodeEnumOsRu:         "Ossetic (Russia)",
	// 	LanguageCodeEnumPa:           "Punjabi",
	// 	LanguageCodeEnumPaArab:       "Punjabi (Arabic)",
	// 	LanguageCodeEnumPaArabPk:     "Punjabi (Arabic, Pakistan)",
	// 	LanguageCodeEnumPaGuru:       "Punjabi (Gurmukhi)",
	// 	LanguageCodeEnumPaGuruIn:     "Punjabi (Gurmukhi, India)",
	// 	LanguageCodeEnumPcm:          "Nigerian Pidgin",
	// 	LanguageCodeEnumPcmNg:        "Nigerian Pidgin (Nigeria)",
	// 	LanguageCodeEnumPl:           "Polish",
	// 	LanguageCodeEnumPlPl:         "Polish (Poland)",
	// 	LanguageCodeEnumPrg:          "Prussian",
	// 	LanguageCodeEnumPs:           "Pashto",
	// 	LanguageCodeEnumPsAf:         "Pashto (Afghanistan)",
	// 	LanguageCodeEnumPsPk:         "Pashto (Pakistan)",
	// 	LanguageCodeEnumPt:           "Portuguese",
	// 	LanguageCodeEnumPtAo:         "Portuguese (Angola)",
	// 	LanguageCodeEnumPtBr:         "Portuguese (Brazil)",
	// 	LanguageCodeEnumPtCh:         "Portuguese (Switzerland)",
	// 	LanguageCodeEnumPtCv:         "Portuguese (Cape Verde)",
	// 	LanguageCodeEnumPtGq:         "Portuguese (Equatorial Guinea)",
	// 	LanguageCodeEnumPtGw:         "Portuguese (Guinea-Bissau)",
	// 	LanguageCodeEnumPtLu:         "Portuguese (Luxembourg)",
	// 	LanguageCodeEnumPtMo:         "Portuguese (Macao SAR China)",
	// 	LanguageCodeEnumPtMz:         "Portuguese (Mozambique)",
	// 	LanguageCodeEnumPtPt:         "Portuguese (Portugal)",
	// 	LanguageCodeEnumPtSt:         "Portuguese (S\u00e3o Tom\u00e9 & Pr\u00edncipe)",
	// 	LanguageCodeEnumPtTl:         "Portuguese (Timor-Leste)",
	// 	LanguageCodeEnumQu:           "Quechua",
	// 	LanguageCodeEnumQuBo:         "Quechua (Bolivia)",
	// 	LanguageCodeEnumQuEc:         "Quechua (Ecuador)",
	// 	LanguageCodeEnumQuPe:         "Quechua (Peru)",
	// 	LanguageCodeEnumRm:           "Romansh",
	// 	LanguageCodeEnumRmCh:         "Romansh (Switzerland)",
	// 	LanguageCodeEnumRn:           "Rundi",
	// 	LanguageCodeEnumRnBi:         "Rundi (Burundi)",
	// 	LanguageCodeEnumRo:           "Romanian",
	// 	LanguageCodeEnumRoMd:         "Romanian (Moldova)",
	// 	LanguageCodeEnumRoRo:         "Romanian (Romania)",
	// 	LanguageCodeEnumRof:          "Rombo",
	// 	LanguageCodeEnumRofTz:        "Rombo (Tanzania)",
	// 	LanguageCodeEnumRu:           "Russian",
	// 	LanguageCodeEnumRuBy:         "Russian (Belarus)",
	// 	LanguageCodeEnumRuKg:         "Russian (Kyrgyzstan)",
	// 	LanguageCodeEnumRuKz:         "Russian (Kazakhstan)",
	// 	LanguageCodeEnumRuMd:         "Russian (Moldova)",
	// 	LanguageCodeEnumRuRu:         "Russian (Russia)",
	// 	LanguageCodeEnumRuUa:         "Russian (Ukraine)",
	// 	LanguageCodeEnumRw:           "Kinyarwanda",
	// 	LanguageCodeEnumRwRw:         "Kinyarwanda (Rwanda)",
	// 	LanguageCodeEnumRwk:          "Rwa",
	// 	LanguageCodeEnumRwkTz:        "Rwa (Tanzania)",
	// 	LanguageCodeEnumSah:          "Sakha",
	// 	LanguageCodeEnumSahRu:        "Sakha (Russia)",
	// 	LanguageCodeEnumSaq:          "Samburu",
	// 	LanguageCodeEnumSaqKe:        "Samburu (Kenya)",
	// 	LanguageCodeEnumSat:          "Santali",
	// 	LanguageCodeEnumSatOlck:      "Santali (Ol Chiki)",
	// 	LanguageCodeEnumSatOlckIn:    "Santali (Ol Chiki, India)",
	// 	LanguageCodeEnumSbp:          "Sangu",
	// 	LanguageCodeEnumSbpTz:        "Sangu (Tanzania)",
	// 	LanguageCodeEnumSd:           "Sindhi",
	// 	LanguageCodeEnumSdArab:       "Sindhi (Arabic)",
	// 	LanguageCodeEnumSdArabPk:     "Sindhi (Arabic, Pakistan)",
	// 	LanguageCodeEnumSdDeva:       "Sindhi (Devanagari)",
	// 	LanguageCodeEnumSdDevaIn:     "Sindhi (Devanagari, India)",
	// 	LanguageCodeEnumSe:           "Northern Sami",
	// 	LanguageCodeEnumSeFi:         "Northern Sami (Finland)",
	// 	LanguageCodeEnumSeNo:         "Northern Sami (Norway)",
	// 	LanguageCodeEnumSeSe:         "Northern Sami (Sweden)",
	// 	LanguageCodeEnumSeh:          "Sena",
	// 	LanguageCodeEnumSehMz:        "Sena (Mozambique)",
	// 	LanguageCodeEnumSes:          "Koyraboro Senni",
	// 	LanguageCodeEnumSesMl:        "Koyraboro Senni (Mali)",
	// 	LanguageCodeEnumSg:           "Sango",
	// 	LanguageCodeEnumSgCf:         "Sango (Central African Republic)",
	// 	LanguageCodeEnumShi:          "Tachelhit",
	// 	LanguageCodeEnumShiLatn:      "Tachelhit (Latin)",
	// 	LanguageCodeEnumShiLatnMa:    "Tachelhit (Latin, Morocco)",
	// 	LanguageCodeEnumShiTfng:      "Tachelhit (Tifinagh)",
	// 	LanguageCodeEnumShiTfngMa:    "Tachelhit (Tifinagh, Morocco)",
	// 	LanguageCodeEnumSi:           "Sinhala",
	// 	LanguageCodeEnumSiLk:         "Sinhala (Sri Lanka)",
	// 	LanguageCodeEnumSk:           "Slovak",
	// 	LanguageCodeEnumSkSk:         "Slovak (Slovakia)",
	// 	LanguageCodeEnumSl:           "Slovenian",
	// 	LanguageCodeEnumSlSi:         "Slovenian (Slovenia)",
	// 	LanguageCodeEnumSmn:          "Inari Sami",
	// 	LanguageCodeEnumSmnFi:        "Inari Sami (Finland)",
	// 	LanguageCodeEnumSn:           "Shona",
	// 	LanguageCodeEnumSnZw:         "Shona (Zimbabwe)",
	// 	LanguageCodeEnumSo:           "Somali",
	// 	LanguageCodeEnumSoDj:         "Somali (Djibouti)",
	// 	LanguageCodeEnumSoEt:         "Somali (Ethiopia)",
	// 	LanguageCodeEnumSoKe:         "Somali (Kenya)",
	// 	LanguageCodeEnumSoSo:         "Somali (Somalia)",
	// 	LanguageCodeEnumSq:           "Albanian",
	// 	LanguageCodeEnumSqAl:         "Albanian (Albania)",
	// 	LanguageCodeEnumSqMk:         "Albanian (North Macedonia)",
	// 	LanguageCodeEnumSqXk:         "Albanian (Kosovo)",
	// 	LanguageCodeEnumSr:           "Serbian",
	// 	LanguageCodeEnumSrCyrl:       "Serbian (Cyrillic)",
	// 	LanguageCodeEnumSrCyrlBa:     "Serbian (Cyrillic, Bosnia & Herzegovina)",
	// 	LanguageCodeEnumSrCyrlMe:     "Serbian (Cyrillic, Montenegro)",
	// 	LanguageCodeEnumSrCyrlRs:     "Serbian (Cyrillic, Serbia)",
	// 	LanguageCodeEnumSrCyrlXk:     "Serbian (Cyrillic, Kosovo)",
	// 	LanguageCodeEnumSrLatn:       "Serbian (Latin)",
	// 	LanguageCodeEnumSrLatnBa:     "Serbian (Latin, Bosnia & Herzegovina)",
	// 	LanguageCodeEnumSrLatnMe:     "Serbian (Latin, Montenegro)",
	// 	LanguageCodeEnumSrLatnRs:     "Serbian (Latin, Serbia)",
	// 	LanguageCodeEnumSrLatnXk:     "Serbian (Latin, Kosovo)",
	// 	LanguageCodeEnumSu:           "Sundanese",
	// 	LanguageCodeEnumSuLatn:       "Sundanese (Latin)",
	// 	LanguageCodeEnumSuLatnID:     "Sundanese (Latin, Indonesia)",
	// 	LanguageCodeEnumSv:           "Swedish",
	// 	LanguageCodeEnumSvAx:         "Swedish (\u00c5land Islands)",
	// 	LanguageCodeEnumSvFi:         "Swedish (Finland)",
	// 	LanguageCodeEnumSvSe:         "Swedish (Sweden)",
	// 	LanguageCodeEnumSw:           "Swahili",
	// 	LanguageCodeEnumSwCd:         "Swahili (Congo - Kinshasa)",
	// 	LanguageCodeEnumSwKe:         "Swahili (Kenya)",
	// 	LanguageCodeEnumSwTz:         "Swahili (Tanzania)",
	// 	LanguageCodeEnumSwUg:         "Swahili (Uganda)",
	// 	LanguageCodeEnumTa:           "Tamil",
	// 	LanguageCodeEnumTaIn:         "Tamil (India)",
	// 	LanguageCodeEnumTaLk:         "Tamil (Sri Lanka)",
	// 	LanguageCodeEnumTaMy:         "Tamil (Malaysia)",
	// 	LanguageCodeEnumTaSg:         "Tamil (Singapore)",
	// 	LanguageCodeEnumTe:           "Telugu",
	// 	LanguageCodeEnumTeIn:         "Telugu (India)",
	// 	LanguageCodeEnumTeo:          "Teso",
	// 	LanguageCodeEnumTeoKe:        "Teso (Kenya)",
	// 	LanguageCodeEnumTeoUg:        "Teso (Uganda)",
	// 	LanguageCodeEnumTg:           "Tajik",
	// 	LanguageCodeEnumTgTj:         "Tajik (Tajikistan)",
	// 	LanguageCodeEnumTh:           "Thai",
	// 	LanguageCodeEnumThTh:         "Thai (Thailand)",
	// 	LanguageCodeEnumTi:           "Tigrinya",
	// 	LanguageCodeEnumTiEr:         "Tigrinya (Eritrea)",
	// 	LanguageCodeEnumTiEt:         "Tigrinya (Ethiopia)",
	// 	LanguageCodeEnumTk:           "Turkmen",
	// 	LanguageCodeEnumTkTm:         "Turkmen (Turkmenistan)",
	// 	LanguageCodeEnumTo:           "Tongan",
	// 	LanguageCodeEnumToTo:         "Tongan (Tonga)",
	// 	LanguageCodeEnumTr:           "Turkish",
	// 	LanguageCodeEnumTrCy:         "Turkish (Cyprus)",
	// 	LanguageCodeEnumTrTr:         "Turkish (Turkey)",
	// 	LanguageCodeEnumTt:           "Tatar",
	// 	LanguageCodeEnumTtRu:         "Tatar (Russia)",
	// 	LanguageCodeEnumTwq:          "Tasawaq",
	// 	LanguageCodeEnumTwqNe:        "Tasawaq (Niger)",
	// 	LanguageCodeEnumTzm:          "Central Atlas Tamazight",
	// 	LanguageCodeEnumTzmMa:        "Central Atlas Tamazight (Morocco)",
	// 	LanguageCodeEnumUg:           "Uyghur",
	// 	LanguageCodeEnumUgCn:         "Uyghur (China)",
	// 	LanguageCodeEnumUk:           "Ukrainian",
	// 	LanguageCodeEnumUkUa:         "Ukrainian (Ukraine)",
	// 	LanguageCodeEnumUr:           "Urdu",
	// 	LanguageCodeEnumUrIn:         "Urdu (India)",
	// 	LanguageCodeEnumUrPk:         "Urdu (Pakistan)",
	// 	LanguageCodeEnumUz:           "Uzbek",
	// 	LanguageCodeEnumUzArab:       "Uzbek (Arabic)",
	// 	LanguageCodeEnumUzArabAf:     "Uzbek (Arabic, Afghanistan)",
	// 	LanguageCodeEnumUzCyrl:       "Uzbek (Cyrillic)",
	// 	LanguageCodeEnumUzCyrlUz:     "Uzbek (Cyrillic, Uzbekistan)",
	// 	LanguageCodeEnumUzLatn:       "Uzbek (Latin)",
	// 	LanguageCodeEnumUzLatnUz:     "Uzbek (Latin, Uzbekistan)",
	// 	LanguageCodeEnumVai:          "Vai",
	// 	LanguageCodeEnumVaiLatn:      "Vai (Latin)",
	// 	LanguageCodeEnumVaiLatnLr:    "Vai (Latin, Liberia)",
	// 	LanguageCodeEnumVaiVaii:      "Vai (Vai)",
	// 	LanguageCodeEnumVaiVaiiLr:    "Vai (Vai, Liberia)",
	// 	LanguageCodeEnumVi:           "Vietnamese",
	// 	LanguageCodeEnumViVn:         "Vietnamese (Vietnam)",
	// 	LanguageCodeEnumVo:           "Volap\u00fck",
	// 	LanguageCodeEnumVun:          "Vunjo",
	// 	LanguageCodeEnumVunTz:        "Vunjo (Tanzania)",
	// 	LanguageCodeEnumWae:          "Walser",
	// 	LanguageCodeEnumWaeCh:        "Walser (Switzerland)",
	// 	LanguageCodeEnumWo:           "Wolof",
	// 	LanguageCodeEnumWoSn:         "Wolof (Senegal)",
	// 	LanguageCodeEnumXh:           "Xhosa",
	// 	LanguageCodeEnumXhZa:         "Xhosa (South Africa)",
	// 	LanguageCodeEnumXog:          "Soga",
	// 	LanguageCodeEnumXogUg:        "Soga (Uganda)",
	// 	LanguageCodeEnumYav:          "Yangben",
	// 	LanguageCodeEnumYavCm:        "Yangben (Cameroon)",
	// 	LanguageCodeEnumYi:           "Yiddish",
	// 	LanguageCodeEnumYo:           "Yoruba",
	// 	LanguageCodeEnumYoBj:         "Yoruba (Benin)",
	// 	LanguageCodeEnumYoNg:         "Yoruba (Nigeria)",
	// 	LanguageCodeEnumYue:          "Cantonese",
	// 	LanguageCodeEnumYueHans:      "Cantonese (Simplified)",
	// 	LanguageCodeEnumYueHansCn:    "Cantonese (Simplified, China)",
	// 	LanguageCodeEnumYueHant:      "Cantonese (Traditional)",
	// 	LanguageCodeEnumYueHantHk:    "Cantonese (Traditional, Hong Kong SAR China)",
	// 	LanguageCodeEnumZgh:          "Standard Moroccan Tamazight",
	// 	LanguageCodeEnumZghMa:        "Standard Moroccan Tamazight (Morocco)",
	// 	LanguageCodeEnumZh:           "Chinese",
	// 	LanguageCodeEnumZhHans:       "Chinese (Simplified)",
	// 	LanguageCodeEnumZhHansCn:     "Chinese (Simplified, China)",
	// 	LanguageCodeEnumZhHansHk:     "Chinese (Simplified, Hong Kong SAR China)",
	// 	LanguageCodeEnumZhHansMo:     "Chinese (Simplified, Macao SAR China)",
	// 	LanguageCodeEnumZhHansSg:     "Chinese (Simplified, Singapore)",
	// 	LanguageCodeEnumZhHant:       "Chinese (Traditional)",
	// 	LanguageCodeEnumZhHantHk:     "Chinese (Traditional, Hong Kong SAR China)",
	// 	LanguageCodeEnumZhHantMo:     "Chinese (Traditional, Macao SAR China)",
	// 	LanguageCodeEnumZhHantTw:     "Chinese (Traditional, Taiwan)",
	// 	LanguageCodeEnumZu:           "Zulu",
	// 	LanguageCodeEnumZuZa:         "Zulu (South Africa)",
	// }
	RestrictedUsernames = map[string]bool{
		"all":      true,
		"channel":  true,
		"sitename": true,
		"system":   true,
		"admin":    true,
	}

	allCountryCodes := model.AllCountryCode()
	for _, code := range allCountryCodes {
		MULTIPLE_COUNTRIES_MAX_LENGTH += len(code)
	}
	MULTIPLE_COUNTRIES_MAX_LENGTH += len(allCountryCodes) - 1
}

// TaxType is for unifying tax type object that comes from tax gateway
type TaxType struct {
	Code         string
	Descriptiton string
}
