// Code generated by mockery v2.23.2. DO NOT EDIT.

// Regenerate this file using `make store-mocks`.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	boil "github.com/volatiletech/sqlboiler/v4/boil"

	model "github.com/sitename/sitename/model"

	model_helper "github.com/sitename/sitename/model_helper"
)

// ShippingZoneStore is an autogenerated mock type for the ShippingZoneStore type
type ShippingZoneStore struct {
	mock.Mock
}

// CountByOptions provides a mock function with given fields: options
func (_m *ShippingZoneStore) CountByOptions(options model_helper.ShippingZoneFilterOption) (int64, error) {
	ret := _m.Called(options)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(model_helper.ShippingZoneFilterOption) (int64, error)); ok {
		return rf(options)
	}
	if rf, ok := ret.Get(0).(func(model_helper.ShippingZoneFilterOption) int64); ok {
		r0 = rf(options)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(model_helper.ShippingZoneFilterOption) error); ok {
		r1 = rf(options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: tx, ids
func (_m *ShippingZoneStore) Delete(tx boil.ContextTransactor, ids []string) (int64, error) {
	ret := _m.Called(tx, ids)

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(boil.ContextTransactor, []string) (int64, error)); ok {
		return rf(tx, ids)
	}
	if rf, ok := ret.Get(0).(func(boil.ContextTransactor, []string) int64); ok {
		r0 = rf(tx, ids)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(boil.ContextTransactor, []string) error); ok {
		r1 = rf(tx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FilterByOption provides a mock function with given fields: option
func (_m *ShippingZoneStore) FilterByOption(option model_helper.ShippingZoneFilterOption) (model.ShippingZoneSlice, error) {
	ret := _m.Called(option)

	var r0 model.ShippingZoneSlice
	var r1 error
	if rf, ok := ret.Get(0).(func(model_helper.ShippingZoneFilterOption) (model.ShippingZoneSlice, error)); ok {
		return rf(option)
	}
	if rf, ok := ret.Get(0).(func(model_helper.ShippingZoneFilterOption) model.ShippingZoneSlice); ok {
		r0 = rf(option)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.ShippingZoneSlice)
		}
	}

	if rf, ok := ret.Get(1).(func(model_helper.ShippingZoneFilterOption) error); ok {
		r1 = rf(option)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *ShippingZoneStore) Get(id string) (*model.ShippingZone, error) {
	ret := _m.Called(id)

	var r0 *model.ShippingZone
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.ShippingZone, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *model.ShippingZone); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShippingZone)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: tx, shippingZone
func (_m *ShippingZoneStore) Upsert(tx boil.ContextTransactor, shippingZone model.ShippingZone) (*model.ShippingZone, error) {
	ret := _m.Called(tx, shippingZone)

	var r0 *model.ShippingZone
	var r1 error
	if rf, ok := ret.Get(0).(func(boil.ContextTransactor, model.ShippingZone) (*model.ShippingZone, error)); ok {
		return rf(tx, shippingZone)
	}
	if rf, ok := ret.Get(0).(func(boil.ContextTransactor, model.ShippingZone) *model.ShippingZone); ok {
		r0 = rf(tx, shippingZone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShippingZone)
		}
	}

	if rf, ok := ret.Get(1).(func(boil.ContextTransactor, model.ShippingZone) error); ok {
		r1 = rf(tx, shippingZone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewShippingZoneStore interface {
	mock.TestingT
	Cleanup(func())
}

// NewShippingZoneStore creates a new instance of ShippingZoneStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewShippingZoneStore(t mockConstructorTestingTNewShippingZoneStore) *ShippingZoneStore {
	mock := &ShippingZoneStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
