DROP INDEX IF EXISTS preorder_reservations_checkout_line_id;
DROP INDEX IF EXISTS preorder_reservations_reserved_until;
DROP INDEX IF EXISTS preorder_reservations_checkout_line_id_product_variant_channel_listing_id;
DROP TABLE IF EXISTS preorder_reservations;
