// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// VariantMedium is an object representing the database table.
type VariantMedium struct {
	ID        string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	Variantid null.String `boil:"variantid" json:"variantid,omitempty" toml:"variantid" yaml:"variantid,omitempty"`
	Mediaid   null.String `boil:"mediaid" json:"mediaid,omitempty" toml:"mediaid" yaml:"mediaid,omitempty"`

	R *variantMediumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L variantMediumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var VariantMediumColumns = struct {
	ID        string
	Variantid string
	Mediaid   string
}{
	ID:        "id",
	Variantid: "variantid",
	Mediaid:   "mediaid",
}

var VariantMediumTableColumns = struct {
	ID        string
	Variantid string
	Mediaid   string
}{
	ID:        "variant_media.id",
	Variantid: "variant_media.variantid",
	Mediaid:   "variant_media.mediaid",
}

// Generated where

var VariantMediumWhere = struct {
	ID        whereHelperstring
	Variantid whereHelpernull_String
	Mediaid   whereHelpernull_String
}{
	ID:        whereHelperstring{field: "\"variant_media\".\"id\""},
	Variantid: whereHelpernull_String{field: "\"variant_media\".\"variantid\""},
	Mediaid:   whereHelpernull_String{field: "\"variant_media\".\"mediaid\""},
}

// VariantMediumRels is where relationship names are stored.
var VariantMediumRels = struct {
	MediaidProductMedium    string
	VariantidProductVariant string
}{
	MediaidProductMedium:    "MediaidProductMedium",
	VariantidProductVariant: "VariantidProductVariant",
}

// variantMediumR is where relationships are stored.
type variantMediumR struct {
	MediaidProductMedium    *ProductMedium  `boil:"MediaidProductMedium" json:"MediaidProductMedium" toml:"MediaidProductMedium" yaml:"MediaidProductMedium"`
	VariantidProductVariant *ProductVariant `boil:"VariantidProductVariant" json:"VariantidProductVariant" toml:"VariantidProductVariant" yaml:"VariantidProductVariant"`
}

// NewStruct creates a new relationship struct
func (*variantMediumR) NewStruct() *variantMediumR {
	return &variantMediumR{}
}

func (r *variantMediumR) GetMediaidProductMedium() *ProductMedium {
	if r == nil {
		return nil
	}
	return r.MediaidProductMedium
}

func (r *variantMediumR) GetVariantidProductVariant() *ProductVariant {
	if r == nil {
		return nil
	}
	return r.VariantidProductVariant
}

// variantMediumL is where Load methods for each relationship are stored.
type variantMediumL struct{}

var (
	variantMediumAllColumns            = []string{"id", "variantid", "mediaid"}
	variantMediumColumnsWithoutDefault = []string{"id"}
	variantMediumColumnsWithDefault    = []string{"variantid", "mediaid"}
	variantMediumPrimaryKeyColumns     = []string{"id"}
	variantMediumGeneratedColumns      = []string{}
)

type (
	// VariantMediumSlice is an alias for a slice of pointers to VariantMedium.
	// This should almost always be used instead of []VariantMedium.
	VariantMediumSlice []*VariantMedium
	// VariantMediumHook is the signature for custom VariantMedium hook methods
	VariantMediumHook func(context.Context, boil.ContextExecutor, *VariantMedium) error

	variantMediumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	variantMediumType                 = reflect.TypeOf(&VariantMedium{})
	variantMediumMapping              = queries.MakeStructMapping(variantMediumType)
	variantMediumPrimaryKeyMapping, _ = queries.BindMapping(variantMediumType, variantMediumMapping, variantMediumPrimaryKeyColumns)
	variantMediumInsertCacheMut       sync.RWMutex
	variantMediumInsertCache          = make(map[string]insertCache)
	variantMediumUpdateCacheMut       sync.RWMutex
	variantMediumUpdateCache          = make(map[string]updateCache)
	variantMediumUpsertCacheMut       sync.RWMutex
	variantMediumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var variantMediumAfterSelectHooks []VariantMediumHook

var variantMediumBeforeInsertHooks []VariantMediumHook
var variantMediumAfterInsertHooks []VariantMediumHook

var variantMediumBeforeUpdateHooks []VariantMediumHook
var variantMediumAfterUpdateHooks []VariantMediumHook

var variantMediumBeforeDeleteHooks []VariantMediumHook
var variantMediumAfterDeleteHooks []VariantMediumHook

var variantMediumBeforeUpsertHooks []VariantMediumHook
var variantMediumAfterUpsertHooks []VariantMediumHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *VariantMedium) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range variantMediumAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *VariantMedium) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range variantMediumBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *VariantMedium) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range variantMediumAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *VariantMedium) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range variantMediumBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *VariantMedium) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range variantMediumAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *VariantMedium) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range variantMediumBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *VariantMedium) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range variantMediumAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *VariantMedium) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range variantMediumBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *VariantMedium) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range variantMediumAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddVariantMediumHook registers your hook function for all future operations.
func AddVariantMediumHook(hookPoint boil.HookPoint, variantMediumHook VariantMediumHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		variantMediumAfterSelectHooks = append(variantMediumAfterSelectHooks, variantMediumHook)
	case boil.BeforeInsertHook:
		variantMediumBeforeInsertHooks = append(variantMediumBeforeInsertHooks, variantMediumHook)
	case boil.AfterInsertHook:
		variantMediumAfterInsertHooks = append(variantMediumAfterInsertHooks, variantMediumHook)
	case boil.BeforeUpdateHook:
		variantMediumBeforeUpdateHooks = append(variantMediumBeforeUpdateHooks, variantMediumHook)
	case boil.AfterUpdateHook:
		variantMediumAfterUpdateHooks = append(variantMediumAfterUpdateHooks, variantMediumHook)
	case boil.BeforeDeleteHook:
		variantMediumBeforeDeleteHooks = append(variantMediumBeforeDeleteHooks, variantMediumHook)
	case boil.AfterDeleteHook:
		variantMediumAfterDeleteHooks = append(variantMediumAfterDeleteHooks, variantMediumHook)
	case boil.BeforeUpsertHook:
		variantMediumBeforeUpsertHooks = append(variantMediumBeforeUpsertHooks, variantMediumHook)
	case boil.AfterUpsertHook:
		variantMediumAfterUpsertHooks = append(variantMediumAfterUpsertHooks, variantMediumHook)
	}
}

// One returns a single variantMedium record from the query.
func (q variantMediumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*VariantMedium, error) {
	o := &VariantMedium{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for variant_media")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all VariantMedium records from the query.
func (q variantMediumQuery) All(ctx context.Context, exec boil.ContextExecutor) (VariantMediumSlice, error) {
	var o []*VariantMedium

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to VariantMedium slice")
	}

	if len(variantMediumAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all VariantMedium records in the query.
func (q variantMediumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count variant_media rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q variantMediumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if variant_media exists")
	}

	return count > 0, nil
}

// MediaidProductMedium pointed to by the foreign key.
func (o *VariantMedium) MediaidProductMedium(mods ...qm.QueryMod) productMediumQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.Mediaid),
	}

	queryMods = append(queryMods, mods...)

	return ProductMedia(queryMods...)
}

// VariantidProductVariant pointed to by the foreign key.
func (o *VariantMedium) VariantidProductVariant(mods ...qm.QueryMod) productVariantQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.Variantid),
	}

	queryMods = append(queryMods, mods...)

	return ProductVariants(queryMods...)
}

// LoadMediaidProductMedium allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (variantMediumL) LoadMediaidProductMedium(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVariantMedium interface{}, mods queries.Applicator) error {
	var slice []*VariantMedium
	var object *VariantMedium

	if singular {
		var ok bool
		object, ok = maybeVariantMedium.(*VariantMedium)
		if !ok {
			object = new(VariantMedium)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVariantMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVariantMedium))
			}
		}
	} else {
		s, ok := maybeVariantMedium.(*[]*VariantMedium)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVariantMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVariantMedium))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &variantMediumR{}
		}
		if !queries.IsNil(object.Mediaid) {
			args = append(args, object.Mediaid)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &variantMediumR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.Mediaid) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.Mediaid) {
				args = append(args, obj.Mediaid)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`product_media`),
		qm.WhereIn(`product_media.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ProductMedium")
	}

	var resultSlice []*ProductMedium
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ProductMedium")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for product_media")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for product_media")
	}

	if len(productMediumAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.MediaidProductMedium = foreign
		if foreign.R == nil {
			foreign.R = &productMediumR{}
		}
		foreign.R.MediaidVariantMedia = append(foreign.R.MediaidVariantMedia, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.Mediaid, foreign.ID) {
				local.R.MediaidProductMedium = foreign
				if foreign.R == nil {
					foreign.R = &productMediumR{}
				}
				foreign.R.MediaidVariantMedia = append(foreign.R.MediaidVariantMedia, local)
				break
			}
		}
	}

	return nil
}

// LoadVariantidProductVariant allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (variantMediumL) LoadVariantidProductVariant(ctx context.Context, e boil.ContextExecutor, singular bool, maybeVariantMedium interface{}, mods queries.Applicator) error {
	var slice []*VariantMedium
	var object *VariantMedium

	if singular {
		var ok bool
		object, ok = maybeVariantMedium.(*VariantMedium)
		if !ok {
			object = new(VariantMedium)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeVariantMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeVariantMedium))
			}
		}
	} else {
		s, ok := maybeVariantMedium.(*[]*VariantMedium)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeVariantMedium)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeVariantMedium))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &variantMediumR{}
		}
		if !queries.IsNil(object.Variantid) {
			args = append(args, object.Variantid)
		}

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &variantMediumR{}
			}

			for _, a := range args {
				if queries.Equal(a, obj.Variantid) {
					continue Outer
				}
			}

			if !queries.IsNil(obj.Variantid) {
				args = append(args, obj.Variantid)
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`product_variants`),
		qm.WhereIn(`product_variants.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ProductVariant")
	}

	var resultSlice []*ProductVariant
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ProductVariant")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for product_variants")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for product_variants")
	}

	if len(productVariantAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.VariantidProductVariant = foreign
		if foreign.R == nil {
			foreign.R = &productVariantR{}
		}
		foreign.R.VariantidVariantMedia = append(foreign.R.VariantidVariantMedia, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.Variantid, foreign.ID) {
				local.R.VariantidProductVariant = foreign
				if foreign.R == nil {
					foreign.R = &productVariantR{}
				}
				foreign.R.VariantidVariantMedia = append(foreign.R.VariantidVariantMedia, local)
				break
			}
		}
	}

	return nil
}

// SetMediaidProductMedium of the variantMedium to the related item.
// Sets o.R.MediaidProductMedium to related.
// Adds o to related.R.MediaidVariantMedia.
func (o *VariantMedium) SetMediaidProductMedium(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ProductMedium) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"variant_media\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"mediaid"}),
		strmangle.WhereClause("\"", "\"", 2, variantMediumPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.Mediaid, related.ID)
	if o.R == nil {
		o.R = &variantMediumR{
			MediaidProductMedium: related,
		}
	} else {
		o.R.MediaidProductMedium = related
	}

	if related.R == nil {
		related.R = &productMediumR{
			MediaidVariantMedia: VariantMediumSlice{o},
		}
	} else {
		related.R.MediaidVariantMedia = append(related.R.MediaidVariantMedia, o)
	}

	return nil
}

// RemoveMediaidProductMedium relationship.
// Sets o.R.MediaidProductMedium to nil.
// Removes o from all passed in related items' relationships struct.
func (o *VariantMedium) RemoveMediaidProductMedium(ctx context.Context, exec boil.ContextExecutor, related *ProductMedium) error {
	var err error

	queries.SetScanner(&o.Mediaid, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("mediaid")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.MediaidProductMedium = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.MediaidVariantMedia {
		if queries.Equal(o.Mediaid, ri.Mediaid) {
			continue
		}

		ln := len(related.R.MediaidVariantMedia)
		if ln > 1 && i < ln-1 {
			related.R.MediaidVariantMedia[i] = related.R.MediaidVariantMedia[ln-1]
		}
		related.R.MediaidVariantMedia = related.R.MediaidVariantMedia[:ln-1]
		break
	}
	return nil
}

// SetVariantidProductVariant of the variantMedium to the related item.
// Sets o.R.VariantidProductVariant to related.
// Adds o to related.R.VariantidVariantMedia.
func (o *VariantMedium) SetVariantidProductVariant(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ProductVariant) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"variant_media\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"variantid"}),
		strmangle.WhereClause("\"", "\"", 2, variantMediumPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.Variantid, related.ID)
	if o.R == nil {
		o.R = &variantMediumR{
			VariantidProductVariant: related,
		}
	} else {
		o.R.VariantidProductVariant = related
	}

	if related.R == nil {
		related.R = &productVariantR{
			VariantidVariantMedia: VariantMediumSlice{o},
		}
	} else {
		related.R.VariantidVariantMedia = append(related.R.VariantidVariantMedia, o)
	}

	return nil
}

// RemoveVariantidProductVariant relationship.
// Sets o.R.VariantidProductVariant to nil.
// Removes o from all passed in related items' relationships struct.
func (o *VariantMedium) RemoveVariantidProductVariant(ctx context.Context, exec boil.ContextExecutor, related *ProductVariant) error {
	var err error

	queries.SetScanner(&o.Variantid, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("variantid")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.VariantidProductVariant = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.VariantidVariantMedia {
		if queries.Equal(o.Variantid, ri.Variantid) {
			continue
		}

		ln := len(related.R.VariantidVariantMedia)
		if ln > 1 && i < ln-1 {
			related.R.VariantidVariantMedia[i] = related.R.VariantidVariantMedia[ln-1]
		}
		related.R.VariantidVariantMedia = related.R.VariantidVariantMedia[:ln-1]
		break
	}
	return nil
}

// VariantMedia retrieves all the records using an executor.
func VariantMedia(mods ...qm.QueryMod) variantMediumQuery {
	mods = append(mods, qm.From("\"variant_media\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"variant_media\".*"})
	}

	return variantMediumQuery{q}
}

// FindVariantMedium retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindVariantMedium(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*VariantMedium, error) {
	variantMediumObj := &VariantMedium{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"variant_media\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, variantMediumObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from variant_media")
	}

	if err = variantMediumObj.doAfterSelectHooks(ctx, exec); err != nil {
		return variantMediumObj, err
	}

	return variantMediumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *VariantMedium) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no variant_media provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(variantMediumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	variantMediumInsertCacheMut.RLock()
	cache, cached := variantMediumInsertCache[key]
	variantMediumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			variantMediumAllColumns,
			variantMediumColumnsWithDefault,
			variantMediumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(variantMediumType, variantMediumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(variantMediumType, variantMediumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"variant_media\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"variant_media\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into variant_media")
	}

	if !cached {
		variantMediumInsertCacheMut.Lock()
		variantMediumInsertCache[key] = cache
		variantMediumInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the VariantMedium.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *VariantMedium) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	variantMediumUpdateCacheMut.RLock()
	cache, cached := variantMediumUpdateCache[key]
	variantMediumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			variantMediumAllColumns,
			variantMediumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update variant_media, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"variant_media\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, variantMediumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(variantMediumType, variantMediumMapping, append(wl, variantMediumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update variant_media row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for variant_media")
	}

	if !cached {
		variantMediumUpdateCacheMut.Lock()
		variantMediumUpdateCache[key] = cache
		variantMediumUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q variantMediumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for variant_media")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for variant_media")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o VariantMediumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), variantMediumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"variant_media\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, variantMediumPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in variantMedium slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all variantMedium")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *VariantMedium) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no variant_media provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(variantMediumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	variantMediumUpsertCacheMut.RLock()
	cache, cached := variantMediumUpsertCache[key]
	variantMediumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			variantMediumAllColumns,
			variantMediumColumnsWithDefault,
			variantMediumColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			variantMediumAllColumns,
			variantMediumPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert variant_media, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(variantMediumPrimaryKeyColumns))
			copy(conflict, variantMediumPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"variant_media\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(variantMediumType, variantMediumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(variantMediumType, variantMediumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert variant_media")
	}

	if !cached {
		variantMediumUpsertCacheMut.Lock()
		variantMediumUpsertCache[key] = cache
		variantMediumUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single VariantMedium record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *VariantMedium) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no VariantMedium provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), variantMediumPrimaryKeyMapping)
	sql := "DELETE FROM \"variant_media\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from variant_media")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for variant_media")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q variantMediumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no variantMediumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from variant_media")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for variant_media")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o VariantMediumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(variantMediumBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), variantMediumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"variant_media\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, variantMediumPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from variantMedium slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for variant_media")
	}

	if len(variantMediumAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *VariantMedium) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindVariantMedium(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VariantMediumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := VariantMediumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), variantMediumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"variant_media\".* FROM \"variant_media\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, variantMediumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in VariantMediumSlice")
	}

	*o = slice

	return nil
}

// VariantMediumExists checks if the VariantMedium row exists.
func VariantMediumExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"variant_media\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if variant_media exists")
	}

	return exists, nil
}

// Exists checks if the VariantMedium row exists.
func (o *VariantMedium) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return VariantMediumExists(ctx, exec, o.ID)
}
