// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testWishlists(t *testing.T) {
	t.Parallel()

	query := Wishlists()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testWishlistsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Wishlists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWishlistsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Wishlists().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Wishlists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWishlistsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WishlistSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Wishlists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWishlistsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := WishlistExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Wishlist exists: %s", err)
	}
	if !e {
		t.Errorf("Expected WishlistExists to return true, but got false.")
	}
}

func testWishlistsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	wishlistFound, err := FindWishlist(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if wishlistFound == nil {
		t.Error("want a record, got nil")
	}
}

func testWishlistsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Wishlists().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testWishlistsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Wishlists().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testWishlistsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	wishlistOne := &Wishlist{}
	wishlistTwo := &Wishlist{}
	if err = randomize.Struct(seed, wishlistOne, wishlistDBTypes, false, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}
	if err = randomize.Struct(seed, wishlistTwo, wishlistDBTypes, false, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = wishlistOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = wishlistTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Wishlists().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testWishlistsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	wishlistOne := &Wishlist{}
	wishlistTwo := &Wishlist{}
	if err = randomize.Struct(seed, wishlistOne, wishlistDBTypes, false, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}
	if err = randomize.Struct(seed, wishlistTwo, wishlistDBTypes, false, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = wishlistOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = wishlistTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Wishlists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func wishlistBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Wishlist) error {
	*o = Wishlist{}
	return nil
}

func wishlistAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Wishlist) error {
	*o = Wishlist{}
	return nil
}

func wishlistAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Wishlist) error {
	*o = Wishlist{}
	return nil
}

func wishlistBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Wishlist) error {
	*o = Wishlist{}
	return nil
}

func wishlistAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Wishlist) error {
	*o = Wishlist{}
	return nil
}

func wishlistBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Wishlist) error {
	*o = Wishlist{}
	return nil
}

func wishlistAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Wishlist) error {
	*o = Wishlist{}
	return nil
}

func wishlistBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Wishlist) error {
	*o = Wishlist{}
	return nil
}

func wishlistAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Wishlist) error {
	*o = Wishlist{}
	return nil
}

func testWishlistsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Wishlist{}
	o := &Wishlist{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, wishlistDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Wishlist object: %s", err)
	}

	AddWishlistHook(boil.BeforeInsertHook, wishlistBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	wishlistBeforeInsertHooks = []WishlistHook{}

	AddWishlistHook(boil.AfterInsertHook, wishlistAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	wishlistAfterInsertHooks = []WishlistHook{}

	AddWishlistHook(boil.AfterSelectHook, wishlistAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	wishlistAfterSelectHooks = []WishlistHook{}

	AddWishlistHook(boil.BeforeUpdateHook, wishlistBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	wishlistBeforeUpdateHooks = []WishlistHook{}

	AddWishlistHook(boil.AfterUpdateHook, wishlistAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	wishlistAfterUpdateHooks = []WishlistHook{}

	AddWishlistHook(boil.BeforeDeleteHook, wishlistBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	wishlistBeforeDeleteHooks = []WishlistHook{}

	AddWishlistHook(boil.AfterDeleteHook, wishlistAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	wishlistAfterDeleteHooks = []WishlistHook{}

	AddWishlistHook(boil.BeforeUpsertHook, wishlistBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	wishlistBeforeUpsertHooks = []WishlistHook{}

	AddWishlistHook(boil.AfterUpsertHook, wishlistAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	wishlistAfterUpsertHooks = []WishlistHook{}
}

func testWishlistsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Wishlists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWishlistsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(wishlistColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Wishlists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWishlistToManyWishlistidWishlistItems(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wishlist
	var b, c WishlistItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, wishlistItemDBTypes, false, wishlistItemColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, wishlistItemDBTypes, false, wishlistItemColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.Wishlistid, a.ID)
	queries.Assign(&c.Wishlistid, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.WishlistidWishlistItems().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.Wishlistid, b.Wishlistid) {
			bFound = true
		}
		if queries.Equal(v.Wishlistid, c.Wishlistid) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := WishlistSlice{&a}
	if err = a.L.LoadWishlistidWishlistItems(ctx, tx, false, (*[]*Wishlist)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.WishlistidWishlistItems); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.WishlistidWishlistItems = nil
	if err = a.L.LoadWishlistidWishlistItems(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.WishlistidWishlistItems); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testWishlistToManyAddOpWishlistidWishlistItems(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wishlist
	var b, c, d, e WishlistItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, wishlistDBTypes, false, strmangle.SetComplement(wishlistPrimaryKeyColumns, wishlistColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*WishlistItem{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, wishlistItemDBTypes, false, strmangle.SetComplement(wishlistItemPrimaryKeyColumns, wishlistItemColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*WishlistItem{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddWishlistidWishlistItems(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.Wishlistid) {
			t.Error("foreign key was wrong value", a.ID, first.Wishlistid)
		}
		if !queries.Equal(a.ID, second.Wishlistid) {
			t.Error("foreign key was wrong value", a.ID, second.Wishlistid)
		}

		if first.R.WishlistidWishlist != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.WishlistidWishlist != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.WishlistidWishlistItems[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.WishlistidWishlistItems[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.WishlistidWishlistItems().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testWishlistToManySetOpWishlistidWishlistItems(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wishlist
	var b, c, d, e WishlistItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, wishlistDBTypes, false, strmangle.SetComplement(wishlistPrimaryKeyColumns, wishlistColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*WishlistItem{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, wishlistItemDBTypes, false, strmangle.SetComplement(wishlistItemPrimaryKeyColumns, wishlistItemColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetWishlistidWishlistItems(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.WishlistidWishlistItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetWishlistidWishlistItems(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.WishlistidWishlistItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.Wishlistid) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.Wishlistid) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.Wishlistid) {
		t.Error("foreign key was wrong value", a.ID, d.Wishlistid)
	}
	if !queries.Equal(a.ID, e.Wishlistid) {
		t.Error("foreign key was wrong value", a.ID, e.Wishlistid)
	}

	if b.R.WishlistidWishlist != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.WishlistidWishlist != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.WishlistidWishlist != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.WishlistidWishlist != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.WishlistidWishlistItems[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.WishlistidWishlistItems[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testWishlistToManyRemoveOpWishlistidWishlistItems(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wishlist
	var b, c, d, e WishlistItem

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, wishlistDBTypes, false, strmangle.SetComplement(wishlistPrimaryKeyColumns, wishlistColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*WishlistItem{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, wishlistItemDBTypes, false, strmangle.SetComplement(wishlistItemPrimaryKeyColumns, wishlistItemColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddWishlistidWishlistItems(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.WishlistidWishlistItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveWishlistidWishlistItems(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.WishlistidWishlistItems().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.Wishlistid) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.Wishlistid) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.WishlistidWishlist != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.WishlistidWishlist != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.WishlistidWishlist != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.WishlistidWishlist != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.WishlistidWishlistItems) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.WishlistidWishlistItems[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.WishlistidWishlistItems[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testWishlistToOneUserUsingUseridUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Wishlist
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.Userid, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.UseridUser().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *User) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := WishlistSlice{&local}
	if err = local.L.LoadUseridUser(ctx, tx, false, (*[]*Wishlist)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UseridUser == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.UseridUser = nil
	if err = local.L.LoadUseridUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.UseridUser == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testWishlistToOneSetOpUserUsingUseridUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wishlist
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, wishlistDBTypes, false, strmangle.SetComplement(wishlistPrimaryKeyColumns, wishlistColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUseridUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.UseridUser != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UseridWishlist != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.Userid, x.ID) {
			t.Error("foreign key was wrong value", a.Userid)
		}

		zero := reflect.Zero(reflect.TypeOf(a.Userid))
		reflect.Indirect(reflect.ValueOf(&a.Userid)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.Userid, x.ID) {
			t.Error("foreign key was wrong value", a.Userid, x.ID)
		}
	}
}

func testWishlistToOneRemoveOpUserUsingUseridUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Wishlist
	var b User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, wishlistDBTypes, false, strmangle.SetComplement(wishlistPrimaryKeyColumns, wishlistColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetUseridUser(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveUseridUser(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.UseridUser().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.UseridUser != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.Userid) {
		t.Error("foreign key value should be nil")
	}

	if b.R.UseridWishlist != nil {
		t.Error("failed to remove a from b's relationships")
	}

}

func testWishlistsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWishlistsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WishlistSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWishlistsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Wishlists().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	wishlistDBTypes = map[string]string{`ID`: `character varying`, `Token`: `character varying`, `Userid`: `character varying`, `Createat`: `bigint`}
	_               = bytes.MinRead
)

func testWishlistsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(wishlistPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(wishlistAllColumns) == len(wishlistPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Wishlists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testWishlistsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(wishlistAllColumns) == len(wishlistPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Wishlist{}
	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Wishlists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, wishlistDBTypes, true, wishlistPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(wishlistAllColumns, wishlistPrimaryKeyColumns) {
		fields = wishlistAllColumns
	} else {
		fields = strmangle.SetComplement(
			wishlistAllColumns,
			wishlistPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := WishlistSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testWishlistsUpsert(t *testing.T) {
	t.Parallel()

	if len(wishlistAllColumns) == len(wishlistPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Wishlist{}
	if err = randomize.Struct(seed, &o, wishlistDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Wishlist: %s", err)
	}

	count, err := Wishlists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, wishlistDBTypes, false, wishlistPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Wishlist struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Wishlist: %s", err)
	}

	count, err = Wishlists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
